#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_desktop_privacy
short_description: Manages GNOME GSettings for org.gnome.desktop.privacy
description:
  - This module allows for the configuration of GSettings keys within the 'org.gnome.desktop.privacy' schema.
  - It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  hide-identity:
    description:
      - "Controls visibility of personal information"
      - "If set to true, the system will make an effort to
      not divulge the user’s identity on screen or on the network."
    type: bool
    default: False
  hide-identity_locked:
    description:
      - "If set to true, locks the 'hide-identity' key to prevent user modification."
    type: bool
    default: false
  show-full-name-in-top-bar:
    description:
      - "Show full name in the user menu"
      - "Whether the users full name is shown in the user menu or not."
    type: bool
    default: True
  show-full-name-in-top-bar_locked:
    description:
      - "If set to true, locks the 'show-full-name-in-top-bar' key to prevent user modification."
    type: bool
    default: false
  remove-old-trash-files:
    description:
      - "Whether to remove old files from the trash automatically"
      - "If TRUE, automatically remove files from the trash
      when they are older than “old-files-age” days."
    type: bool
    default: False
  remove-old-trash-files_locked:
    description:
      - "If set to true, locks the 'remove-old-trash-files' key to prevent user modification."
    type: bool
    default: false
  remove-old-temp-files:
    description:
      - "Whether to remove old temporary files automatically"
      - "If TRUE, automatically remove temporary files
      when they are older than “old-files-age” days."
    type: bool
    default: False
  remove-old-temp-files_locked:
    description:
      - "If set to true, locks the 'remove-old-temp-files' key to prevent user modification."
    type: bool
    default: false
  old-files-age:
    description:
      - "Number of days to keep trash and temporary files"
      - "Consider trash and temporary files old after
      this many days."
    type: str
    default: '30'
  old-files-age_locked:
    description:
      - "If set to true, locks the 'old-files-age' key to prevent user modification."
    type: bool
    default: false
  remember-recent-files:
    description:
      - "Whether to remember recently used files"
      - "If FALSE, applications will not remember recently
        used files."
    type: bool
    default: True
  remember-recent-files_locked:
    description:
      - "If set to true, locks the 'remember-recent-files' key to prevent user modification."
    type: bool
    default: false
  recent-files-max-age:
    description:
      - "Number of days to remember recently used files for"
      - "Recently used files will be remembered for this many days.
        If set to 0, recent files will not be remembered; if set to -1, they
        will be retained indefinitely."
    type: int
    default: -1
  recent-files-max-age_locked:
    description:
      - "If set to true, locks the 'recent-files-max-age' key to prevent user modification."
    type: bool
    default: false
  remember-app-usage:
    description:
      - "Whether to remember application usage"
      - "If FALSE, application usage will not be monitored
        and recorded."
    type: bool
    default: True
  remember-app-usage_locked:
    description:
      - "If set to true, locks the 'remember-app-usage' key to prevent user modification."
    type: bool
    default: false
  send-software-usage-stats:
    description:
      - "Send statistics when applications are removed or installed"
      - "If FALSE, no anonymous installation or removal information will be sent to the vendor."
    type: bool
    default: False
  send-software-usage-stats_locked:
    description:
      - "If set to true, locks the 'send-software-usage-stats' key to prevent user modification."
    type: bool
    default: false
  report-technical-problems:
    description:
      - "Send reports of technical problems to the vendor"
      - "If TRUE, anonymized reports will be sent automatically to the vendor."
    type: bool
    default: False
  report-technical-problems_locked:
    description:
      - "If set to true, locks the 'report-technical-problems' key to prevent user modification."
    type: bool
    default: false
  disable-microphone:
    description:
      - "Don’t allow applications to access the microphone"
      - "If TRUE, applications should not use the microphone."
    type: bool
    default: False
  disable-microphone_locked:
    description:
      - "If set to true, locks the 'disable-microphone' key to prevent user modification."
    type: bool
    default: false
  disable-camera:
    description:
      - "Don’t allow applications to access the camera"
      - "If TRUE, applications should not use the camera."
    type: bool
    default: False
  disable-camera_locked:
    description:
      - "If set to true, locks the 'disable-camera' key to prevent user modification."
    type: bool
    default: false
  disable-sound-output:
    description:
      - "Don’t allow applications to output sound"
      - "If TRUE, applications should not make sound."
    type: bool
    default: False
  disable-sound-output_locked:
    description:
      - "If set to true, locks the 'disable-sound-output' key to prevent user modification."
    type: bool
    default: false
  usb-protection:
    description:
      - "Whether to protect USB devices"
      - "If the USBGuard service is present and this setting is
        enabled, USB devices will be protected as configured in the
        usb-protection-level setting.
      "
    type: bool
    default: True
  usb-protection_locked:
    description:
      - "If set to true, locks the 'usb-protection' key to prevent user modification."
    type: bool
    default: false
  usb-protection-level:
    description:
      - "When USB devices should be rejected"
      - "
        If set to “lockscreen”, only when the lock screen is present new USB devices will
        be rejected; if set to “always”, all new USB devices will always be rejected.
      "
    type: str
    default: 'lockscreen'
  usb-protection-level_locked:
    description:
      - "If set to true, locks the 'usb-protection-level' key to prevent user modification."
    type: bool
    default: false
  privacy-screen:
    description:
      - "Whether the privacy screen is enabled"
      - "If the underlying hardware has privacy screen support and
        this setting is enabled, the panels supporting this technology will be
        obscured from lateral view.
      "
    type: bool
    default: False
  privacy-screen_locked:
    description:
      - "If set to true, locks the 'privacy-screen' key to prevent user modification."
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.desktop.privacy
  org_gnome_desktop_privacy:
    hide-identity: False
    hide-identity_locked: true
    show-full-name-in-top-bar: True
    show-full-name-in-top-bar_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'hide-identity': {
            'type': 'bool',
            'default': False
        },
        'show-full-name-in-top-bar': {
            'type': 'bool',
            'default': True
        },
        'remove-old-trash-files': {
            'type': 'bool',
            'default': False
        },
        'remove-old-temp-files': {
            'type': 'bool',
            'default': False
        },
        'old-files-age': {
            'type': 'str',
            'default': '30'
        },
        'remember-recent-files': {
            'type': 'bool',
            'default': True
        },
        'recent-files-max-age': {
            'type': 'int',
            'default': -1
        },
        'remember-app-usage': {
            'type': 'bool',
            'default': True
        },
        'send-software-usage-stats': {
            'type': 'bool',
            'default': False
        },
        'report-technical-problems': {
            'type': 'bool',
            'default': False
        },
        'disable-microphone': {
            'type': 'bool',
            'default': False
        },
        'disable-camera': {
            'type': 'bool',
            'default': False
        },
        'disable-sound-output': {
            'type': 'bool',
            'default': False
        },
        'usb-protection': {
            'type': 'bool',
            'default': True
        },
        'usb-protection-level': {
            'type': 'str',
            'default': 'lockscreen'
        },
        'privacy-screen': {
            'type': 'bool',
            'default': False
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_desktop_privacy")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_desktop_privacy")

    schema_full_path = "/org/gnome/desktop/privacy/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f"'{param_value}'"
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()