#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_system_proxy
short_description: Manages GNOME GSettings for org.gnome.system.proxy
description:
  - This module allows for the configuration of GSettings keys within the 'org.gnome.system.proxy' schema.
  - It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  mode:
    description:
      - "Proxy configuration mode"
      - "
        Select the proxy configuration mode. Supported values are “none”,
        “manual”, “auto”.

        If this is “none”, then proxies are not used.

        If it is “auto”, the autoconfiguration URL described by the
        “autoconfig-url” key is used.

        If it is “manual”, then the proxies described by
        “/system/proxy/http”, “/system/proxy/https”,
        “/system/proxy/ftp” and “/system/proxy/socks” will be used.
        Each of the 4 proxy types is enabled if its “host” key is
        non-empty and its “port” key is non-0.

        If an http proxy is configured, but an https proxy is not,
        then the http proxy is also used for https.

        If a SOCKS proxy is configured, it is used for all protocols,
        except that the http, https, and ftp proxy settings override
        it for those protocols only.
      "
    type: str
    default: 'none'
  mode_locked:
    description:
      - "If set to true, locks the 'mode' key to prevent user modification."
    type: bool
    default: false
  autoconfig-url:
    description:
      - "Automatic proxy configuration URL"
      - "
        URL that provides proxy configuration values. When mode is
        “auto”, this URL is used to look up proxy information for all
        protocols.
      "
    type: str
    default: ''
  autoconfig-url_locked:
    description:
      - "If set to true, locks the 'autoconfig-url' key to prevent user modification."
    type: bool
    default: false
  ignore-hosts:
    description:
      - "Non-proxy hosts"
      - "
        This key contains a list of hosts which are connected to directly,
        rather than via the proxy (if it is active). The values can be
        hostnames, domains (using an initial wildcard like *.foo.com), IP host
        addresses (both IPv4 and IPv6) and network addresses with a netmask
        (something like 192.168.0.0/24).
      "
    type: str
    default: '[ 'localhost', '127.0.0.0/8', '::1' ]'
  ignore-hosts_locked:
    description:
      - "If set to true, locks the 'ignore-hosts' key to prevent user modification."
    type: bool
    default: false
  use-same-proxy:
    description:
      - "Use HTTP proxy for all protocols"
      - "
        Whether to use the HTTP proxy for all protocols or not.
      "
    type: bool
    default: True
  use-same-proxy_locked:
    description:
      - "If set to true, locks the 'use-same-proxy' key to prevent user modification."
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.system.proxy
  org_gnome_system_proxy:
    mode: 'none'
    mode_locked: true
    autoconfig-url: ''
    autoconfig-url_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'mode': {
            'type': 'str',
            'default': 'none'
        },
        'autoconfig-url': {
            'type': 'str',
            'default': ''
        },
        'ignore-hosts': {
            'type': 'str',
            'default': '[ 'localhost', '127.0.0.0/8', '::1' ]'
        },
        'use-same-proxy': {
            'type': 'bool',
            'default': True
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_system_proxy")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_system_proxy")

    schema_full_path = "/system/proxy/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f"'{param_value}'"
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()