#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_desktop_break_reminders_eyesight
short_description: Manages GNOME GSettings for org.gnome.desktop.break-reminders.eyesight
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.desktop.break-reminders.eyesight' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  interval-seconds:
    description:
    - Time between breaks
    - The time between rest breaks, in seconds.
    type: str
    default: 1200

  interval-seconds_locked:
    description:
    - >
      If set to true, locks the 'interval-seconds' key to prevent user modification.
    type: bool
    default: false
  duration-seconds:
    description:
    - Duration of each break
    - The duration of each rest break, in seconds.
    type: str
    default: 20

  duration-seconds_locked:
    description:
    - >
      If set to true, locks the 'duration-seconds' key to prevent user modification.
    type: bool
    default: false
  delay-seconds:
    description:
    - Amount to delay break if requested
    - The amount to delay taking the break by, if the user requests a delay, in seconds.
    type: str
    default: 180

  delay-seconds_locked:
    description:
    - >
      If set to true, locks the 'delay-seconds' key to prevent user modification.
    type: bool
    default: false
  fade-screen:
    description:
    - Fade screen during breaks
    - True to fade the screen during rest breaks.
    type: bool
    default: true

  fade-screen_locked:
    description:
    - >
      If set to true, locks the 'fade-screen' key to prevent user modification.
    type: bool
    default: false
  lock-screen:
    description:
    - Lock screen during breaks
    - True to lock the screen during rest breaks.
    type: bool
    default: false

  lock-screen_locked:
    description:
    - >
      If set to true, locks the 'lock-screen' key to prevent user modification.
    type: bool
    default: false
  play-sound:
    description:
    - Play sound when a break finishes
    - True to play a sound when a break finishes.
    type: bool
    default: true

  play-sound_locked:
    description:
    - >
      If set to true, locks the 'play-sound' key to prevent user modification.
    type: bool
    default: false
  notify:
    description:
    - Notify when a break is due
    - True to emit a notification when a break is due to start.
    type: bool
    default: true

  notify_locked:
    description:
    - >
      If set to true, locks the 'notify' key to prevent user modification.
    type: bool
    default: false
  notify-upcoming:
    description:
    - Notify when a break is upcoming
    - True to emit a notification a few minutes before a break is due.
    type: bool
    default: false

  notify-upcoming_locked:
    description:
    - >
      If set to true, locks the 'notify-upcoming' key to prevent user modification.
    type: bool
    default: false
  notify-overdue:
    description:
    - Notify when a break is overdue
    - True to emit a notification when a break is overdue.
    type: bool
    default: true

  notify-overdue_locked:
    description:
    - >
      If set to true, locks the 'notify-overdue' key to prevent user modification.
    type: bool
    default: false
  countdown:
    description:
    - Notify when a break is due
    - True to show a prominent countdown shortly before a break is due.
    type: bool
    default: false

  countdown_locked:
    description:
    - >
      If set to true, locks the 'countdown' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.desktop.break-reminders.eyesight
  org_gnome_desktop_break_reminders_eyesight:
    interval-seconds: 1200

    duration-seconds: 20

    delay-seconds: 180

    fade-screen: true

    lock-screen: false

    play-sound: true

    notify: true

    notify-upcoming: false

    notify-overdue: true

    countdown: false

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'interval-seconds': {
            'default': 1200,
            'type': 'str',
            'gtype':'u',
        },
        'duration-seconds': {
            'default': 20,
            'type': 'str',
            'gtype':'u',
        },
        'delay-seconds': {
            'default': 180,
            'type': 'str',
            'gtype':'u',
        },
        'fade-screen': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'lock-screen': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'play-sound': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'notify': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'notify-upcoming': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'notify-overdue': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'countdown': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.desktop.break-reminders.eyesight")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.desktop.break-reminders.eyesight")

    schema_full_path = "/org/gnome/desktop/break-reminders/eyesight/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
