#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_fedorahosted_background-logo-extension
short_description: Manages GNOME GSettings for org.fedorahosted.background-logo-extension
description:
  - This module allows for the configuration of GSettings keys within the 'org.fedorahosted.background-logo-extension' schema.
  - It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  logo-file:
    description:
      - "Logo file"
      - "The full logo file path"
    type: str
    default: '/usr/share/fedora-logos/fedora_lightbackground.svg'
  logo-file_locked:
    description:
      - "If set to true, locks the 'logo-file' key to prevent user modification."
    type: bool
    default: false
  logo-file-dark:
    description:
      - "Logo file in dark mode"
      - "The full logo file path for dark mode"
    type: str
    default: '/usr/share/fedora-logos/fedora_darkbackground.svg'
  logo-file-dark_locked:
    description:
      - "If set to true, locks the 'logo-file-dark' key to prevent user modification."
    type: bool
    default: false
  logo-position:
    description:
      - "Logo position"
      - "
        The position logo of the logo; valid values are 'center',
        'bottom-left', 'bottom-center', 'bottom-right',
        'top-left', 'top-center' and 'top-right'
      "
    type: str
    default: 'bottom-right'
  logo-position_locked:
    description:
      - "If set to true, locks the 'logo-position' key to prevent user modification."
    type: bool
    default: false
  logo-size:
    description:
      - "Logo size"
      - "The logo size in percent relative to the screen width"
    type: str
    default: '9.0'
  logo-size_locked:
    description:
      - "If set to true, locks the 'logo-size' key to prevent user modification."
    type: bool
    default: false
  logo-border:
    description:
      - "Logo border"
      - "The border around the logo"
    type: str
    default: '50'
  logo-border_locked:
    description:
      - "If set to true, locks the 'logo-border' key to prevent user modification."
    type: bool
    default: false
  logo-opacity:
    description:
      - "Logo opacity"
      - "The opacity of the logo"
    type: str
    default: '255'
  logo-opacity_locked:
    description:
      - "If set to true, locks the 'logo-opacity' key to prevent user modification."
    type: bool
    default: false
  logo-always-visible:
    description:
      - "Logo always visible"
      - "Show the logo even on a non default background"
    type: bool
    default: False
  logo-always-visible_locked:
    description:
      - "If set to true, locks the 'logo-always-visible' key to prevent user modification."
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.fedorahosted.background-logo-extension
  org_fedorahosted_background-logo-extension:
    logo-file: '/usr/share/fedora-logos/fedora_lightbackground.svg'
    logo-file_locked: true
    logo-file-dark: '/usr/share/fedora-logos/fedora_darkbackground.svg'
    logo-file-dark_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'logo-file': {
            'type': 'str',
            'default': '/usr/share/fedora-logos/fedora_lightbackground.svg'
        },
        'logo-file-dark': {
            'type': 'str',
            'default': '/usr/share/fedora-logos/fedora_darkbackground.svg'
        },
        'logo-position': {
            'type': 'str',
            'default': 'bottom-right'
        },
        'logo-size': {
            'type': 'str',
            'default': '9.0'
        },
        'logo-border': {
            'type': 'str',
            'default': '50'
        },
        'logo-opacity': {
            'type': 'str',
            'default': '255'
        },
        'logo-always-visible': {
            'type': 'bool',
            'default': False
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_fedorahosted_background-logo-extension")
    lock_file_path = os.path.join(locks_dir, "ansible-org_fedorahosted_background-logo-extension")

    schema_full_path = "/org/fedorahosted/background-logo-extension/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f"'{param_value}'"
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()