#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_shell_keybindings
short_description: Manages GNOME GSettings for org.gnome.shell.keybindings
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.shell.keybindings' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  shift-overview-up:
    description:
    - Keybinding to shift between overview states
    - Keybinding to shift between session, window picker and app grid
    type: str
    default:
    - SuperAltUp

  shift-overview-up_locked:
    description:
    - >
      If set to true, locks the 'shift-overview-up' key to prevent user modification.
    type: bool
    default: false
  shift-overview-down:
    description:
    - Keybinding to shift between overview states
    - Keybinding to shift between app grid, window picker and session
    type: str
    default:
    - SuperAltDown

  shift-overview-down_locked:
    description:
    - >
      If set to true, locks the 'shift-overview-down' key to prevent user modification.
    type: bool
    default: false
  toggle-application-view:
    description:
    - "Keybinding to open the \u201CShow Applications\u201D view"
    - "Keybinding to open the 'Show Applications' view of the Activities\n        Overview."
    type: str
    default:
    - Supera

  toggle-application-view_locked:
    description:
    - >
      If set to true, locks the 'toggle-application-view' key to prevent user modification.
    type: bool
    default: false
  toggle-overview:
    description:
    - Keybinding to open the overview
    - Keybinding to open the Activities Overview.
    type: str
    default: []

  toggle-overview_locked:
    description:
    - >
      If set to true, locks the 'toggle-overview' key to prevent user modification.
    type: bool
    default: false
  toggle-message-tray:
    description:
    - Keybinding to toggle the visibility of the notification list
    - Keybinding to toggle the visibility of the notification list.
    type: str
    default:
    - Superv
    - Superm

  toggle-message-tray_locked:
    description:
    - >
      If set to true, locks the 'toggle-message-tray' key to prevent user modification.
    type: bool
    default: false
  toggle-quick-settings:
    description:
    - Keybinding to toggle the quick settings menu
    - Keybinding to toggle the quick settings menu.
    type: str
    default:
    - Supers

  toggle-quick-settings_locked:
    description:
    - >
      If set to true, locks the 'toggle-quick-settings' key to prevent user modification.
    type: bool
    default: false
  focus-active-notification:
    description:
    - Keybinding to focus the active notification
    - Keybinding to focus the active notification.
    type: str
    default:
    - Supern

  focus-active-notification_locked:
    description:
    - >
      If set to true, locks the 'focus-active-notification' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-1:
    description:
    - Switch to application 1
    - Description - Schema Blank
    type: str
    default:
    - Super1

  switch-to-application-1_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-1' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-2:
    description:
    - Switch to application 2
    - Description - Schema Blank
    type: str
    default:
    - Super2

  switch-to-application-2_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-2' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-3:
    description:
    - Switch to application 3
    - Description - Schema Blank
    type: str
    default:
    - Super3

  switch-to-application-3_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-3' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-4:
    description:
    - Switch to application 4
    - Description - Schema Blank
    type: str
    default:
    - Super4

  switch-to-application-4_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-4' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-5:
    description:
    - Switch to application 5
    - Description - Schema Blank
    type: str
    default:
    - Super5

  switch-to-application-5_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-5' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-6:
    description:
    - Switch to application 6
    - Description - Schema Blank
    type: str
    default:
    - Super6

  switch-to-application-6_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-6' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-7:
    description:
    - Switch to application 7
    - Description - Schema Blank
    type: str
    default:
    - Super7

  switch-to-application-7_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-7' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-8:
    description:
    - Switch to application 8
    - Description - Schema Blank
    type: str
    default:
    - Super8

  switch-to-application-8_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-8' key to prevent user modification.
    type: bool
    default: false
  switch-to-application-9:
    description:
    - Switch to application 9
    - Description - Schema Blank
    type: str
    default:
    - Super9

  switch-to-application-9_locked:
    description:
    - >
      If set to true, locks the 'switch-to-application-9' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-1:
    description:
    - Open a new instance of application 1
    - Description - Schema Blank
    type: str
    default:
    - SuperControl1

  open-new-window-application-1_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-1' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-2:
    description:
    - Open a new instance of application 2
    - Description - Schema Blank
    type: str
    default:
    - SuperControl2

  open-new-window-application-2_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-2' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-3:
    description:
    - Open a new instance of application 3
    - Description - Schema Blank
    type: str
    default:
    - SuperControl3

  open-new-window-application-3_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-3' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-4:
    description:
    - Open a new instance of application 4
    - Description - Schema Blank
    type: str
    default:
    - SuperControl4

  open-new-window-application-4_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-4' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-5:
    description:
    - Open a new instance of application 5
    - Description - Schema Blank
    type: str
    default:
    - SuperControl5

  open-new-window-application-5_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-5' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-6:
    description:
    - Open a new instance of application 6
    - Description - Schema Blank
    type: str
    default:
    - SuperControl6

  open-new-window-application-6_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-6' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-7:
    description:
    - Open a new instance of application 7
    - Description - Schema Blank
    type: str
    default:
    - SuperControl7

  open-new-window-application-7_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-7' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-8:
    description:
    - Open a new instance of application 8
    - Description - Schema Blank
    type: str
    default:
    - SuperControl8

  open-new-window-application-8_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-8' key to prevent user modification.
    type: bool
    default: false
  open-new-window-application-9:
    description:
    - Open a new instance of application 9
    - Description - Schema Blank
    type: str
    default:
    - SuperControl9

  open-new-window-application-9_locked:
    description:
    - >
      If set to true, locks the 'open-new-window-application-9' key to prevent user modification.
    type: bool
    default: false
  show-screenshot-ui:
    description:
    - Take a screenshot interactively
    - Description - Schema Blank
    type: str
    default:
    - Print

  show-screenshot-ui_locked:
    description:
    - >
      If set to true, locks the 'show-screenshot-ui' key to prevent user modification.
    type: bool
    default: false
  show-screen-recording-ui:
    description:
    - Record a screencast interactively
    - Description - Schema Blank
    type: str
    default:
    - CtrlShiftAltR

  show-screen-recording-ui_locked:
    description:
    - >
      If set to true, locks the 'show-screen-recording-ui' key to prevent user modification.
    type: bool
    default: false
  screenshot-window:
    description:
    - Take a screenshot of a window
    - Description - Schema Blank
    type: str
    default:
    - AltPrint

  screenshot-window_locked:
    description:
    - >
      If set to true, locks the 'screenshot-window' key to prevent user modification.
    type: bool
    default: false
  screenshot:
    description:
    - Take a screenshot
    - Description - Schema Blank
    type: str
    default:
    - ShiftPrint

  screenshot_locked:
    description:
    - >
      If set to true, locks the 'screenshot' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.shell.keybindings
  org_gnome_shell_keybindings:
    shift-overview-up:
    - SuperAltUp

    shift-overview-down:
    - SuperAltDown

    toggle-application-view:
    - Supera

    toggle-overview: []

    toggle-message-tray:
    - Superv
    - Superm

    toggle-quick-settings:
    - Supers

    focus-active-notification:
    - Supern

    switch-to-application-1:
    - Super1

    switch-to-application-2:
    - Super2

    switch-to-application-3:
    - Super3

    switch-to-application-4:
    - Super4

    switch-to-application-5:
    - Super5

    switch-to-application-6:
    - Super6

    switch-to-application-7:
    - Super7

    switch-to-application-8:
    - Super8

    switch-to-application-9:
    - Super9

    open-new-window-application-1:
    - SuperControl1

    open-new-window-application-2:
    - SuperControl2

    open-new-window-application-3:
    - SuperControl3

    open-new-window-application-4:
    - SuperControl4

    open-new-window-application-5:
    - SuperControl5

    open-new-window-application-6:
    - SuperControl6

    open-new-window-application-7:
    - SuperControl7

    open-new-window-application-8:
    - SuperControl8

    open-new-window-application-9:
    - SuperControl9

    show-screenshot-ui:
    - Print

    show-screen-recording-ui:
    - CtrlShiftAltR

    screenshot-window:
    - AltPrint

    screenshot:
    - ShiftPrint

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'shift-overview-up': {
            'default': ['SuperAltUp'],
            'type': 'str',
            'gtype':'as',
        },
        'shift-overview-down': {
            'default': ['SuperAltDown'],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-application-view': {
            'default': ['Supera'],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-overview': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-message-tray': {
            'default': ['Superv', 'Superm'],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-quick-settings': {
            'default': ['Supers'],
            'type': 'str',
            'gtype':'as',
        },
        'focus-active-notification': {
            'default': ['Supern'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-1': {
            'default': ['Super1'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-2': {
            'default': ['Super2'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-3': {
            'default': ['Super3'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-4': {
            'default': ['Super4'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-5': {
            'default': ['Super5'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-6': {
            'default': ['Super6'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-7': {
            'default': ['Super7'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-8': {
            'default': ['Super8'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-application-9': {
            'default': ['Super9'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-1': {
            'default': ['SuperControl1'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-2': {
            'default': ['SuperControl2'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-3': {
            'default': ['SuperControl3'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-4': {
            'default': ['SuperControl4'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-5': {
            'default': ['SuperControl5'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-6': {
            'default': ['SuperControl6'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-7': {
            'default': ['SuperControl7'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-8': {
            'default': ['SuperControl8'],
            'type': 'str',
            'gtype':'as',
        },
        'open-new-window-application-9': {
            'default': ['SuperControl9'],
            'type': 'str',
            'gtype':'as',
        },
        'show-screenshot-ui': {
            'default': ['Print'],
            'type': 'str',
            'gtype':'as',
        },
        'show-screen-recording-ui': {
            'default': ['CtrlShiftAltR'],
            'type': 'str',
            'gtype':'as',
        },
        'screenshot-window': {
            'default': ['AltPrint'],
            'type': 'str',
            'gtype':'as',
        },
        'screenshot': {
            'default': ['ShiftPrint'],
            'type': 'str',
            'gtype':'as',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.shell.keybindings")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.shell.keybindings")

    schema_full_path = "/org/gnome/shell/keybindings/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
