#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_system_proxy_http
short_description: Manages GNOME GSettings for org.gnome.system.proxy.http
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.system.proxy.http' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  enabled:
    description:
    - Unused; ignore
    - "This key is not used; HTTP proxying is enabled when the host\n        key is non-empty\
      \ and the port is non-0."
    type: bool
    default: false

  enabled_locked:
    description:
    - >
      If set to true, locks the 'enabled' key to prevent user modification.
    type: bool
    default: false
  host:
    description:
    - HTTP proxy host name
    - The machine name to proxy HTTP through.
    type: str
    default: ''

  host_locked:
    description:
    - >
      If set to true, locks the 'host' key to prevent user modification.
    type: bool
    default: false
  port:
    description:
    - HTTP proxy port
    - "The port on the machine defined by '/system/proxy/http/host' that you\n       \
      \ proxy through."
    type: int
    default: 8080

  port_locked:
    description:
    - >
      If set to true, locks the 'port' key to prevent user modification.
    type: bool
    default: false
  use-authentication:
    description:
    - Authenticate proxy server connections
    - "If true, then connections to the proxy server require authentication.\n       \
      \ The username/password combo is defined by\n        '/system/proxy/http/authentication-user'\
      \ and\n        '/system/proxy/http/authentication-password'.\n\n        This applies\
      \ only to the http proxy; when using a separate\n        https proxy, there is currently\
      \ no way to specify that it\n        should use authentication."
    type: bool
    default: false

  use-authentication_locked:
    description:
    - >
      If set to true, locks the 'use-authentication' key to prevent user modification.
    type: bool
    default: false
  authentication-user:
    description:
    - HTTP proxy username
    - User name to pass as authentication when doing HTTP proxying.
    type: str
    default: ''

  authentication-user_locked:
    description:
    - >
      If set to true, locks the 'authentication-user' key to prevent user modification.
    type: bool
    default: false
  authentication-password:
    description:
    - HTTP proxy password
    - Password to pass as authentication when doing HTTP proxying.
    type: str
    default: ''

  authentication-password_locked:
    description:
    - >
      If set to true, locks the 'authentication-password' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.system.proxy.http
  org_gnome_system_proxy_http:
    enabled: false

    host: ''

    port: 8080

    use-authentication: false

    authentication-user: ''

    authentication-password: ''

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'enabled': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'host': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'port': {
            'default': 8080,
            'type': 'int',
            'gtype':'i',
        },
        'use-authentication': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'authentication-user': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'authentication-password': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.system.proxy.http")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.system.proxy.http")

    schema_full_path = "/system/proxy/http/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
