#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_login_screen
short_description: Manages GNOME GSettings for org.gnome.login-screen
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.login-screen' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  enable-fingerprint-authentication:
    description:
    - Whether or not to allow fingerprint readers for login
    - "The login screen can optionally allow users who have enrolled\n        their fingerprints\
      \ to log in using those prints."
    type: bool
    default: true

  enable-fingerprint-authentication_locked:
    description:
    - >
      If set to true, locks the 'enable-fingerprint-authentication' key to prevent user modification.
    type: bool
    default: false
  enable-smartcard-authentication:
    description:
    - Whether or not to allow smartcard readers for login
    - "The login screen can optionally allow users who have smartcards\n        to log\
      \ in using those smartcards."
    type: bool
    default: true

  enable-smartcard-authentication_locked:
    description:
    - >
      If set to true, locks the 'enable-smartcard-authentication' key to prevent user modification.
    type: bool
    default: false
  enable-password-authentication:
    description:
    - Whether or not to allow passwords for login
    - "The login screen can be configured to disallow password authentication,\n     \
      \   forcing the user to use smartcard or fingerprint authentication."
    type: bool
    default: true

  enable-password-authentication_locked:
    description:
    - >
      If set to true, locks the 'enable-password-authentication' key to prevent user modification.
    type: bool
    default: false
  logo:
    description:
    - Path to small image at top of user list
    - "The login screen can optionally show a small image to provide site\n        administrators\
      \ and distributions a way to display branding."
    type: str
    default: ''

  logo_locked:
    description:
    - >
      If set to true, locks the 'logo' key to prevent user modification.
    type: bool
    default: false
  fallback-logo:
    description:
    - Path to small image at top of user list
    - "The fallback login screen can optionally show a small image to provide\n      \
      \  site administrators and distributions a way to display branding."
    type: str
    default: ''

  fallback-logo_locked:
    description:
    - >
      If set to true, locks the 'fallback-logo' key to prevent user modification.
    type: bool
    default: false
  disable-user-list:
    description:
    - Avoid showing user list
    - "The login screen normally shows a list of available users to log in\n        as.\
      \ This setting can be toggled to disable showing the user list."
    type: bool
    default: false

  disable-user-list_locked:
    description:
    - >
      If set to true, locks the 'disable-user-list' key to prevent user modification.
    type: bool
    default: false
  banner-message-enable:
    description:
    - Enable showing the banner message
    - Set to true to show the banner message text.
    type: bool
    default: false

  banner-message-enable_locked:
    description:
    - >
      If set to true, locks the 'banner-message-enable' key to prevent user modification.
    type: bool
    default: false
  banner-message-text:
    description:
    - Banner message text
    - Text banner message to show in the login window.
    type: str
    default: ''

  banner-message-text_locked:
    description:
    - >
      If set to true, locks the 'banner-message-text' key to prevent user modification.
    type: bool
    default: false
  disable-restart-buttons:
    description:
    - Disable showing the restart buttons
    - Set to true to disable showing the restart buttons in the login window.
    type: bool
    default: false

  disable-restart-buttons_locked:
    description:
    - >
      If set to true, locks the 'disable-restart-buttons' key to prevent user modification.
    type: bool
    default: false
  allowed-failures:
    description:
    - Number of allowed authentication failures
    - "The number of times a user is allowed to attempt authentication, before\n     \
      \   giving up and going back to user selection."
    type: int
    default: 3

  allowed-failures_locked:
    description:
    - >
      If set to true, locks the 'allowed-failures' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.login-screen
  org_gnome_login_screen:
    enable-fingerprint-authentication: true

    enable-smartcard-authentication: true

    enable-password-authentication: true

    logo: ''

    fallback-logo: ''

    disable-user-list: false

    banner-message-enable: false

    banner-message-text: ''

    disable-restart-buttons: false

    allowed-failures: 3

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'enable-fingerprint-authentication': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'enable-smartcard-authentication': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'enable-password-authentication': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'logo': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'fallback-logo': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'disable-user-list': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'banner-message-enable': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'banner-message-text': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'disable-restart-buttons': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'allowed-failures': {
            'default': 3,
            'type': 'int',
            'gtype':'i',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.login-screen")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.login-screen")

    schema_full_path = "/org/gnome/login-screen/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
