#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_gnome_system_monitor_disksview
short_description: Manages GNOME GSettings for org.gnome.gnome-system-monitor.disksview
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.gnome-system-monitor.disksview' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  sort-col:
    description:
    - Disk view sort column
    - Description - Schema Blank
    type: str
    default: directory

  sort-col_locked:
    description:
    - >
      If set to true, locks the 'sort-col' key to prevent user modification.
    type: bool
    default: false
  sort-order:
    description:
    - Disk view sort order
    - Description - Schema Blank
    type: int
    default: 0

  sort-order_locked:
    description:
    - >
      If set to true, locks the 'sort-order' key to prevent user modification.
    type: bool
    default: false
  columns-order:
    description:
    - Disk view columns order
    - Description - Schema Blank
    type: str
    default:
    - device
    - directory
    - type
    - total
    - free
    - available
    - used

  columns-order_locked:
    description:
    - >
      If set to true, locks the 'columns-order' key to prevent user modification.
    type: bool
    default: false
  col-device-width:
    description:
    - "Width of disk view \u201CDevice\u201D column"
    - Description - Schema Blank
    type: int
    default: 100

  col-device-width_locked:
    description:
    - >
      If set to true, locks the 'col-device-width' key to prevent user modification.
    type: bool
    default: false
  col-device-visible:
    description:
    - "Show disk view \u201CDevice\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: true

  col-device-visible_locked:
    description:
    - >
      If set to true, locks the 'col-device-visible' key to prevent user modification.
    type: bool
    default: false
  col-directory-width:
    description:
    - "Width of disk view \u201CDirectory\u201D column"
    - Description - Schema Blank
    type: int
    default: 100

  col-directory-width_locked:
    description:
    - >
      If set to true, locks the 'col-directory-width' key to prevent user modification.
    type: bool
    default: false
  col-directory-visible:
    description:
    - "Show disk view \u201CDirectory\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: true

  col-directory-visible_locked:
    description:
    - >
      If set to true, locks the 'col-directory-visible' key to prevent user modification.
    type: bool
    default: false
  col-type-width:
    description:
    - "Width of disk view \u201CType\u201D column"
    - Description - Schema Blank
    type: int
    default: 50

  col-type-width_locked:
    description:
    - >
      If set to true, locks the 'col-type-width' key to prevent user modification.
    type: bool
    default: false
  col-type-visible:
    description:
    - "Show disk view \u201CType\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: true

  col-type-visible_locked:
    description:
    - >
      If set to true, locks the 'col-type-visible' key to prevent user modification.
    type: bool
    default: false
  col-total-width:
    description:
    - "Width of disk view \u201CTotal\u201D column"
    - Description - Schema Blank
    type: int
    default: 80

  col-total-width_locked:
    description:
    - >
      If set to true, locks the 'col-total-width' key to prevent user modification.
    type: bool
    default: false
  col-total-visible:
    description:
    - "Show disk view \u201CTotal\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: true

  col-total-visible_locked:
    description:
    - >
      If set to true, locks the 'col-total-visible' key to prevent user modification.
    type: bool
    default: false
  col-free-width:
    description:
    - "Width of disk view \u201CFree\u201D column"
    - Description - Schema Blank
    type: int
    default: 80

  col-free-width_locked:
    description:
    - >
      If set to true, locks the 'col-free-width' key to prevent user modification.
    type: bool
    default: false
  col-free-visible:
    description:
    - "Show disk view \u201CFree\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: false

  col-free-visible_locked:
    description:
    - >
      If set to true, locks the 'col-free-visible' key to prevent user modification.
    type: bool
    default: false
  col-available-width:
    description:
    - "Width of disk view \u201CAvailable\u201D column"
    - Description - Schema Blank
    type: int
    default: 80

  col-available-width_locked:
    description:
    - >
      If set to true, locks the 'col-available-width' key to prevent user modification.
    type: bool
    default: false
  col-available-visible:
    description:
    - "Show disk view \u201CAvailable\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: true

  col-available-visible_locked:
    description:
    - >
      If set to true, locks the 'col-available-visible' key to prevent user modification.
    type: bool
    default: false
  col-used-width:
    description:
    - "Width of disk view \u201CUsed\u201D column"
    - Description - Schema Blank
    type: int
    default: 300

  col-used-width_locked:
    description:
    - >
      If set to true, locks the 'col-used-width' key to prevent user modification.
    type: bool
    default: false
  col-used-visible:
    description:
    - "Show disk view \u201CUsed\u201D column on startup"
    - Description - Schema Blank
    type: bool
    default: true

  col-used-visible_locked:
    description:
    - >
      If set to true, locks the 'col-used-visible' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.gnome-system-monitor.disksview
  org_gnome_gnome_system_monitor_disksview:
    sort-col: directory

    sort-order: 0

    columns-order:
    - device
    - directory
    - type
    - total
    - free
    - available
    - used

    col-device-width: 100

    col-device-visible: true

    col-directory-width: 100

    col-directory-visible: true

    col-type-width: 50

    col-type-visible: true

    col-total-width: 80

    col-total-visible: true

    col-free-width: 80

    col-free-visible: false

    col-available-width: 80

    col-available-visible: true

    col-used-width: 300

    col-used-visible: true

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'sort-col': {
            'default': 'directory',
            'type': 'str',
            'gtype':'s',
        },
        'sort-order': {
            'default': 0,
            'type': 'int',
            'gtype':'i',
        },
        'columns-order': {
            'default': ['device', 'directory', 'type', 'total', 'free', 'available', 'used'],
            'type': 'str',
            'gtype':'as',
        },
        'col-device-width': {
            'default': 100,
            'type': 'int',
            'gtype':'i',
        },
        'col-device-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'col-directory-width': {
            'default': 100,
            'type': 'int',
            'gtype':'i',
        },
        'col-directory-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'col-type-width': {
            'default': 50,
            'type': 'int',
            'gtype':'i',
        },
        'col-type-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'col-total-width': {
            'default': 80,
            'type': 'int',
            'gtype':'i',
        },
        'col-total-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'col-free-width': {
            'default': 80,
            'type': 'int',
            'gtype':'i',
        },
        'col-free-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'col-available-width': {
            'default': 80,
            'type': 'int',
            'gtype':'i',
        },
        'col-available-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'col-used-width': {
            'default': 300,
            'type': 'int',
            'gtype':'i',
        },
        'col-used-visible': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.gnome-system-monitor.disksview")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.gnome-system-monitor.disksview")

    schema_full_path = "/org/gnome/gnome-system-monitor/disksview/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
