#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_virt_manager_virt_manager_new_vm
short_description: Manages GNOME GSettings for org.virt-manager.virt-manager.new-vm
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.virt-manager.virt-manager.new-vm' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  graphics-type:
    description:
    - Install selected graphics type for new VM
    - Install selected graphics type for new VM. vnc or spice, system for software configured
      default
    type: str
    default: system

  graphics-type_locked:
    description:
    - >
      If set to true, locks the 'graphics-type' key to prevent user modification.
    type: bool
    default: false
  storage-format:
    description:
    - Use selected format for new VM storage
    - Use selected format when creating new disk images in new VM wizard
    type: str
    default: default

  storage-format_locked:
    description:
    - >
      If set to true, locks the 'storage-format' key to prevent user modification.
    type: bool
    default: false
  cpu-default:
    description:
    - CPU setting to use for new VMs
    - 'CPU setting to use for new VMs. Limited to VMs matching the host architecture.
      Possible values: default (virt-manager default), hv-default (qemu''s default), host-model-only
      (just the model, not the additional features), host-model (libvirt''s host-model
      setting), host-passthrough (libvirt''s host-passthrough setting).'
    type: str
    default: default

  cpu-default_locked:
    description:
    - >
      If set to true, locks the 'cpu-default' key to prevent user modification.
    type: bool
    default: false
  firmware:
    description:
    - Use selected firmware for new VM booting
    - Firmware used for new VMs. Possible values are default and UEFI. The firmware used
      is determined by libvirt unless a specific firmware is selected from the Customize
      dialog.
    type: str
    default: default

  firmware_locked:
    description:
    - >
      If set to true, locks the 'firmware' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.virt-manager.virt-manager.new-vm
  org_virt_manager_virt_manager_new_vm:
    graphics-type: system

    storage-format: default

    cpu-default: default

    firmware: default

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'graphics-type': {
            'default': 'system',
            'type': 'str',
            'gtype':'s',
        },
        'storage-format': {
            'default': 'default',
            'type': 'str',
            'gtype':'s',
        },
        'cpu-default': {
            'default': 'default',
            'type': 'str',
            'gtype':'s',
        },
        'firmware': {
            'default': 'default',
            'type': 'str',
            'gtype':'s',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.virt-manager.virt-manager.new-vm")
    lock_file_path = os.path.join(locks_dir, "ansible-org.virt-manager.virt-manager.new-vm")

    schema_full_path = "/org/virt-manager/virt-manager/new-vm/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
