#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_calculator
short_description: Manages GNOME GSettings for org.gnome.calculator
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.calculator' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  accuracy:
    description:
      - >
        Accuracy value
      - >
        The number of digits displayed after the numeric point
    type: int
    default: 9
  accuracy_locked:
    description:
      - >
        If set to true, locks the 'accuracy' key to prevent user modification.
    type: bool
    default: false
  word-size:
    description:
      - >
        Word size
      - >
        The size of the words used in bitwise operations
    type: int
    default: 64
  word-size_locked:
    description:
      - >
        If set to true, locks the 'word-size' key to prevent user modification.
    type: bool
    default: false
  base:
    description:
      - >
        Numeric Base
      - >
        The numeric base
    type: int
    default: 10
  base_locked:
    description:
      - >
        If set to true, locks the 'base' key to prevent user modification.
    type: bool
    default: false
  show-thousands:
    description:
      - >
        Show Thousands Separators
      - >
        Indicates whether thousands separators are shown in large numbers.
    type: bool
    default: false
  show-thousands_locked:
    description:
      - >
        If set to true, locks the 'show-thousands' key to prevent user modification.
    type: bool
    default: false
  show-zeroes:
    description:
      - >
        Show Trailing Zeroes
      - >
        Indicates whether any trailing zeroes after the numeric point should be shown in the display value.
    type: bool
    default: false
  show-zeroes_locked:
    description:
      - >
        If set to true, locks the 'show-zeroes' key to prevent user modification.
    type: bool
    default: false
  number-format:
    description:
      - >
        Number format
      - >
        The format to display numbers in
    type: str
    default: "automatic"
  number-format_locked:
    description:
      - >
        If set to true, locks the 'number-format' key to prevent user modification.
    type: bool
    default: false
  angle-units:
    description:
      - >
        Angle units
      - >
        The angle units to use
    type: str
    default: "degrees"
  angle-units_locked:
    description:
      - >
        If set to true, locks the 'angle-units' key to prevent user modification.
    type: bool
    default: false
  refresh-interval:
    description:
      - >
        Currency update interval
      - >
        How often the currency exchange rates should be updated. A value of 0 means the currency exchange rates won't be fetched from the network at all.
    type: int
    default: 604800
  refresh-interval_locked:
    description:
      - >
        If set to true, locks the 'refresh-interval' key to prevent user modification.
    type: bool
    default: false
  button-mode:
    description:
      - >
        Button mode
      - >
        The button mode
    type: str
    default: "basic"
  button-mode_locked:
    description:
      - >
        If set to true, locks the 'button-mode' key to prevent user modification.
    type: bool
    default: false
  source-currency:
    description:
      - >
        Source currency
      - >
        Currency of the current calculation
    type: str
    default: ""
  source-currency_locked:
    description:
      - >
        If set to true, locks the 'source-currency' key to prevent user modification.
    type: bool
    default: false
  target-currency:
    description:
      - >
        Target currency
      - >
        Currency to convert the current calculation into
    type: str
    default: ""
  target-currency_locked:
    description:
      - >
        If set to true, locks the 'target-currency' key to prevent user modification.
    type: bool
    default: false
  source-units:
    description:
      - >
        Source units
      - >
        Units of the current calculation
    type: str
    default: "degree"
  source-units_locked:
    description:
      - >
        If set to true, locks the 'source-units' key to prevent user modification.
    type: bool
    default: false
  target-units:
    description:
      - >
        Target units
      - >
        Units to convert the current calculation into
    type: str
    default: "radian"
  target-units_locked:
    description:
      - >
        If set to true, locks the 'target-units' key to prevent user modification.
    type: bool
    default: false
  precision:
    description:
      - >
        Internal precision
      - >
        The internal precision used with the MPFR library
    type: int
    default: 2000
  precision_locked:
    description:
      - >
        If set to true, locks the 'precision' key to prevent user modification.
    type: bool
    default: false
  window-position:
    description:
      - >
        Window position
      - >
        Window position (x and y) of the last closed window.
    type: str
    default: "(-1, -1)"
  window-position_locked:
    description:
      - >
        If set to true, locks the 'window-position' key to prevent user modification.
    type: bool
    default: false
  window-maximized:
    description:
      - >
        Window maximized
      - >
        Whether the last closed window was maximized.
    type: bool
    default: false
  window-maximized_locked:
    description:
      - >
        If set to true, locks the 'window-maximized' key to prevent user modification.
    type: bool
    default: false
  window-size:
    description:
      - >
        Window size
      - >
        Window size (width and height) of the last closed window.
    type: str
    default: "(-1, -1)"
  window-size_locked:
    description:
      - >
        If set to true, locks the 'window-size' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.calculator
  org_gnome_calculator:
    accuracy: 9
    accuracy_locked: true
    word-size: 64
    word-size_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'accuracy': {
            'type': 'int',
            'default': 9
        },
        'word-size': {
            'type': 'int',
            'default': 64
        },
        'base': {
            'type': 'int',
            'default': 10
        },
        'show-thousands': {
            'type': 'bool',
            'default': True
        },
        'show-zeroes': {
            'type': 'bool',
            'default': True
        },
        'number-format': {
            'type': 'str',
            'default': "automatic"
        },
        'angle-units': {
            'type': 'str',
            'default': "degrees"
        },
        'refresh-interval': {
            'type': 'int',
            'default': 604800
        },
        'button-mode': {
            'type': 'str',
            'default': "basic"
        },
        'source-currency': {
            'type': 'str',
            'default': ''
        },
        'target-currency': {
            'type': 'str',
            'default': ''
        },
        'source-units': {
            'type': 'str',
            'default': "degree"
        },
        'target-units': {
            'type': 'str',
            'default': "radian"
        },
        'precision': {
            'type': 'int',
            'default': 2000
        },
        'window-position': {
            'type': 'str',
            'default': "(-1, -1)"
        },
        'window-maximized': {
            'type': 'bool',
            'default': True
        },
        'window-size': {
            'type': 'str',
            'default': "(-1, -1)"
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_calculator")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_calculator")

    schema_full_path = "/org/gnome/calculator/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f"'{param_value}'"
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
