#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gtk_Settings_FileChooser
short_description: Manages GNOME GSettings for org.gtk.Settings.FileChooser
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gtk.Settings.FileChooser' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  last-folder-uri:
    description:
      - >
        Summary - Schema Blank
      - >
        Description - Schema Blank
    type: str
    default: >
             ""
  last-folder-uri_locked:
    description:
      - >
        If set to true, locks the 'last-folder-uri' key to prevent user modification.
    type: bool
    default: false
  location-mode:
    description:
      - >
        Location mode
      - >
        Controls whether the file chooser shows just a path bar, or a visible entry for the filename as well, for the benefit of typing-oriented users. The possible values for these modes are "path-bar" and "filename-entry".
    type: str
    default: >
             path-bar
  location-mode_locked:
    description:
      - >
        If set to true, locks the 'location-mode' key to prevent user modification.
    type: bool
    default: false
  show-hidden:
    description:
      - >
        Show hidden files
      - >
        Controls whether the file chooser shows hidden files or not.
    type: bool
    default: false
  show-hidden_locked:
    description:
      - >
        If set to true, locks the 'show-hidden' key to prevent user modification.
    type: bool
    default: false
  sort-directories-first:
    description:
      - >
        Show folders first
      - >
        If set to true, then folders are shown before files in the list.
    type: bool
    default: false
  sort-directories-first_locked:
    description:
      - >
        If set to true, locks the 'sort-directories-first' key to prevent user modification.
    type: bool
    default: false
  expand-folders:
    description:
      - >
        Expand folders
      - >
        This key is deprecated; do not use it.
    type: bool
    default: false
  expand-folders_locked:
    description:
      - >
        If set to true, locks the 'expand-folders' key to prevent user modification.
    type: bool
    default: false
  show-size-column:
    description:
      - >
        Show file sizes
      - >
        Controls whether the file chooser shows a column with file sizes.
    type: bool
    default: true
  show-size-column_locked:
    description:
      - >
        If set to true, locks the 'show-size-column' key to prevent user modification.
    type: bool
    default: false
  show-type-column:
    description:
      - >
        Show file types
      - >
        Controls whether the file chooser shows a column with file types.
    type: bool
    default: true
  show-type-column_locked:
    description:
      - >
        If set to true, locks the 'show-type-column' key to prevent user modification.
    type: bool
    default: false
  sort-column:
    description:
      - >
        Sort column
      - >
        Can be one of "name", "modified", or "size". It controls which of the columns in the file chooser is used for sorting the list of files.
    type: str
    default: >
             name
  sort-column_locked:
    description:
      - >
        If set to true, locks the 'sort-column' key to prevent user modification.
    type: bool
    default: false
  sort-order:
    description:
      - >
        Sort order
      - >
        Can be one of the strings "ascending" or "descending".
    type: str
    default: >
             ascending
  sort-order_locked:
    description:
      - >
        If set to true, locks the 'sort-order' key to prevent user modification.
    type: bool
    default: false
  window-position:
    description:
      - >
        Window position
      - >
        The (x, y) coordinates of the upper-left corner of the GtkFileChooserDialog's window.
    type: str
    default: >
             (-1, -1)
  window-position_locked:
    description:
      - >
        If set to true, locks the 'window-position' key to prevent user modification.
    type: bool
    default: false
  window-size:
    description:
      - >
        Window size
      - >
        The size (width, height) of the GtkFileChooserDialog's window, in pixels.
    type: str
    default: >
             (-1, -1)
  window-size_locked:
    description:
      - >
        If set to true, locks the 'window-size' key to prevent user modification.
    type: bool
    default: false
  startup-mode:
    description:
      - >
        Startup mode
      - >
        Either "recent" or "cwd"; controls whether the file chooser starts up showing the list of recently-used files, or the contents of the current working directory.
    type: str
    default: >
             recent
  startup-mode_locked:
    description:
      - >
        If set to true, locks the 'startup-mode' key to prevent user modification.
    type: bool
    default: false
  sidebar-width:
    description:
      - >
        Sidebar width
      - >
        Width in pixels of the file chooser's places sidebar.
    type: int
    default: 148
  sidebar-width_locked:
    description:
      - >
        If set to true, locks the 'sidebar-width' key to prevent user modification.
    type: bool
    default: false
  clock-format:
    description:
      - >
        Time format
      - >
        Whether the time is shown in 24h or 12h format.
    type: str
    default: >
             24h
  clock-format_locked:
    description:
      - >
        If set to true, locks the 'clock-format' key to prevent user modification.
    type: bool
    default: false
  date-format:
    description:
      - >
        Date format
      - >
        The amount of detail to show in the Modified column.
    type: str
    default: >
             regular
  date-format_locked:
    description:
      - >
        If set to true, locks the 'date-format' key to prevent user modification.
    type: bool
    default: false
  type-format:
    description:
      - >
        Type format
      - >
        Different ways to show the 'Type' column information. Example outputs for a video mp4 file: 'mime' -> 'video/mp4' 'description' -> 'MPEG-4 video' 'category' -> 'Video'
    type: str
    default: >
             category
  type-format_locked:
    description:
      - >
        If set to true, locks the 'type-format' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gtk.Settings.FileChooser
  org_gtk_Settings_FileChooser:
    last-folder-uri: ""
    last-folder-uri_locked: true
    location-mode: "path-bar"
    location-mode_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'last-folder-uri': {
            'type': 'str',
            'default': ''
        },
        'location-mode': {
            'type': 'str',
            'default': "path-bar"
        },
        'show-hidden': {
            'type': 'bool',
            'default': True
        },
        'sort-directories-first': {
            'type': 'bool',
            'default': True
        },
        'expand-folders': {
            'type': 'bool',
            'default': True
        },
        'show-size-column': {
            'type': 'bool',
            'default': True
        },
        'show-type-column': {
            'type': 'bool',
            'default': True
        },
        'sort-column': {
            'type': 'str',
            'default': "name"
        },
        'sort-order': {
            'type': 'str',
            'default': "ascending"
        },
        'window-position': {
            'type': 'str',
            'default': "(-1, -1)"
        },
        'window-size': {
            'type': 'str',
            'default': "(-1, -1)"
        },
        'startup-mode': {
            'type': 'str',
            'default': "recent"
        },
        'sidebar-width': {
            'type': 'int',
            'default': 148
        },
        'clock-format': {
            'type': 'str',
            'default': "24h"
        },
        'date-format': {
            'type': 'str',
            'default': "regular"
        },
        'type-format': {
            'type': 'str',
            'default': "category"
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gtk_Settings_FileChooser")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gtk_Settings_FileChooser")

    schema_full_path = "/org/gtk/settings/file-chooser/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
