#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_desktop_wm_preferences
short_description: Manages GNOME GSettings for org.gnome.desktop.wm.preferences
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.desktop.wm.preferences' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  mouse-button-modifier:
    description:
      - >
        Modifier to use for modified window click actions
      - >
        Clicking a window while holding down this modifier key will move the window (left click), resize the window (middle click), or show the window menu (right click). The middle and right click operations may be swapped using the “resize-with-right-button” key. Modifier is expressed as “<Alt>” or “<Super>” for example.
    type: str
    default: >
             <Super>
  mouse-button-modifier_locked:
    description:
      - >
        If set to true, locks the 'mouse-button-modifier' key to prevent user modification.
    type: bool
    default: false
  resize-with-right-button:
    description:
      - >
        Whether to resize with the right button
      - >
        Set this to true to resize with the right button and show a menu with the middle button while holding down the key given in “mouse-button-modifier”; set it to false to make it work the opposite way around.
    type: bool
    default: false
  resize-with-right-button_locked:
    description:
      - >
        If set to true, locks the 'resize-with-right-button' key to prevent user modification.
    type: bool
    default: false
  button-layout:
    description:
      - >
        Arrangement of buttons on the titlebar
      - >
        Arrangement of buttons on the titlebar. The value should be a string, such as “menu:minimize,maximize,spacer,close”; the colon separates the left corner of the window from the right corner, and the button names are comma-separated. Duplicate buttons are not allowed. Unknown button names are silently ignored so that buttons can be added in future metacity versions without breaking older versions. A special spacer tag can be used to insert some space between two adjacent buttons.
    type: str
    default: >
             appmenu:close
  button-layout_locked:
    description:
      - >
        If set to true, locks the 'button-layout' key to prevent user modification.
    type: bool
    default: false
  focus-mode:
    description:
      - >
        Window focus mode
      - >
        The window focus mode indicates how windows are activated. It has three possible values; “click” means windows must be clicked in order to focus them, “sloppy” means windows are focused when the mouse enters the window, and “mouse” means windows are focused when the mouse enters the window and unfocused when the mouse leaves the window.
    type: str
    default: >
             click
  focus-mode_locked:
    description:
      - >
        If set to true, locks the 'focus-mode' key to prevent user modification.
    type: bool
    default: false
  focus-new-windows:
    description:
      - >
        Control how new windows get focus
      - >
        This option provides additional control over how newly created windows get focus. It has two possible values; “smart” applies the user’s normal focus mode, and “strict” results in new windows not being given focus automatically.
    type: str
    default: >
             smart
  focus-new-windows_locked:
    description:
      - >
        If set to true, locks the 'focus-new-windows' key to prevent user modification.
    type: bool
    default: false
  raise-on-click:
    description:
      - >
        Whether windows should be raised when their client area is clicked
      - >
        The default, true, indicates that a window will be raised whenever its client area or its frame is clicked. Setting this to false means that a window will not be raised if it is clicked on the client area. To raise it, one can click anywhere in the window’s frame, or Super-click on any part of the window. This mode is useful if one uses many overlapping windows.
    type: bool
    default: true
  raise-on-click_locked:
    description:
      - >
        If set to true, locks the 'raise-on-click' key to prevent user modification.
    type: bool
    default: false
  action-double-click-titlebar:
    description:
      - >
        Action on title bar double-click
      - >
        This option determines the effects of double-clicking on the title bar. Current valid options are “toggle-maximize” which will maximize/unmaximize the window, “toggle-maximize-horizontally” and “toggle-maximize-vertically” which will maximize/unmaximize the window in that direction only, “minimize” which will minimize the window, “menu” which will display the window menu, “lower” which will put the window behind all the others, and “none” which will not do anything.
    type: str
    default: >
             toggle-maximize
  action-double-click-titlebar_locked:
    description:
      - >
        If set to true, locks the 'action-double-click-titlebar' key to prevent user modification.
    type: bool
    default: false
  action-middle-click-titlebar:
    description:
      - >
        Action on title bar middle-click
      - >
        This option determines the effects of middle-clicking on the title bar. Current valid options are “toggle-maximize” which will maximize/unmaximize the window, “toggle-maximize-horizontally” and “toggle-maximize-vertically” which will maximize/unmaximize the window in that direction only, “minimize” which will minimize the window, “menu” which will display the window menu, “lower” which will put the window behind all the others, and “none” which will not do anything.
    type: str
    default: >
             none
  action-middle-click-titlebar_locked:
    description:
      - >
        If set to true, locks the 'action-middle-click-titlebar' key to prevent user modification.
    type: bool
    default: false
  action-right-click-titlebar:
    description:
      - >
        Action on title bar right-click
      - >
        This option determines the effects of right-clicking on the title bar. Current valid options are “toggle-maximize” which will maximize/unmaximize the window, “toggle-maximize-horizontally” and “toggle-maximize-vertically” which will maximize/unmaximize the window in that direction only, “minimize” which will minimize the window, “menu” which will display the window menu, “lower” which will put the window behind all the others, and “none” which will not do anything.
    type: str
    default: >
             menu
  action-right-click-titlebar_locked:
    description:
      - >
        If set to true, locks the 'action-right-click-titlebar' key to prevent user modification.
    type: bool
    default: false
  auto-raise:
    description:
      - >
        Automatically raises the focused window
      - >
        If set to true, and the focus mode is either “sloppy” or “mouse” then the focused window will be automatically raised after a delay specified by the auto-raise-delay key. This is not related to clicking on a window to raise it, nor to entering a window during drag-and-drop.
    type: bool
    default: false
  auto-raise_locked:
    description:
      - >
        If set to true, locks the 'auto-raise' key to prevent user modification.
    type: bool
    default: false
  auto-raise-delay:
    description:
      - >
        Delay in milliseconds for the auto raise option
      - >
        The time delay before raising a window if auto-raise is set to true. The delay is given in thousandths of a second.
    type: int
    default: 500
  auto-raise-delay_locked:
    description:
      - >
        If set to true, locks the 'auto-raise-delay' key to prevent user modification.
    type: bool
    default: false
  theme:
    description:
      - >
        Current theme
      - >
        The theme determines the appearance of window borders, titlebar, and so forth. DEPRECATED: This key is deprecated and ignored.
    type: str
    default: >
             Adwaita
  theme_locked:
    description:
      - >
        If set to true, locks the 'theme' key to prevent user modification.
    type: bool
    default: false
  titlebar-uses-system-font:
    description:
      - >
        Use standard system font in window titles
      - >
        If true, ignore the titlebar-font option, and use the standard application font for window titles.
    type: bool
    default: true
  titlebar-uses-system-font_locked:
    description:
      - >
        If set to true, locks the 'titlebar-uses-system-font' key to prevent user modification.
    type: bool
    default: false
  titlebar-font:
    description:
      - >
        Window title font
      - >
        A font description string describing a font for window titlebars. The size from the description will only be used if the titlebar-font-size option is set to 0. Also, this option is disabled if the titlebar-uses-desktop-font option is set to true.
    type: str
    default: >
             Adwaita Sans Bold 11
  titlebar-font_locked:
    description:
      - >
        If set to true, locks the 'titlebar-font' key to prevent user modification.
    type: bool
    default: false
  num-workspaces:
    description:
      - >
        Number of workspaces
      - >
        Number of workspaces. Must be more than zero, and has a fixed maximum to prevent making the desktop unusable by accidentally asking for too many workspaces.
    type: int
    default: 4
  num-workspaces_locked:
    description:
      - >
        If set to true, locks the 'num-workspaces' key to prevent user modification.
    type: bool
    default: false
  audible-bell:
    description:
      - >
        System Bell is Audible
      - >
        Determines whether applications or the system can generate audible “beeps”; may be used in conjunction with “visual bell” to allow silent “beeps”.
    type: bool
    default: true
  audible-bell_locked:
    description:
      - >
        If set to true, locks the 'audible-bell' key to prevent user modification.
    type: bool
    default: false
  visual-bell:
    description:
      - >
        Enable Visual Bell
      - >
        Turns on a visual indication when an application or the system issues a “bell” or “beep”; useful for the hard-of-hearing and for use in noisy environments.
    type: bool
    default: false
  visual-bell_locked:
    description:
      - >
        If set to true, locks the 'visual-bell' key to prevent user modification.
    type: bool
    default: false
  visual-bell-type:
    description:
      - >
        Visual Bell Type
      - >
        Tells the WM how to implement the visual indication that the system bell or another application “bell” indicator has been rung. Currently there are two valid values, “fullscreen-flash”, which causes a fullscreen white-black flash, and “frame-flash” which causes the titlebar of the application which sent the bell signal to flash. If the application which sent the bell is unknown (as is usually the case for the default “system beep”), the currently focused window’s titlebar is flashed.
    type: str
    default: >
             fullscreen-flash
  visual-bell-type_locked:
    description:
      - >
        If set to true, locks the 'visual-bell-type' key to prevent user modification.
    type: bool
    default: false
  disable-workarounds:
    description:
      - >
        Disable misfeatures that are required by old or broken applications
      - >
        Some applications disregard specifications in ways that result in window manager misfeatures. This option puts the WM in a rigorously correct mode, which gives a more consistent user interface, provided one does not need to run any misbehaving applications.
    type: bool
    default: false
  disable-workarounds_locked:
    description:
      - >
        If set to true, locks the 'disable-workarounds' key to prevent user modification.
    type: bool
    default: false
  workspace-names:
    description:
      - >
        The names of the workspaces
      - >
        Defines the names that should be assigned to workspaces. If the list is too long for the current number of workspaces, names in excess will be ignored. If the list is too short, or includes empty names, missing values will be replaced with the default (“Workspace N”).
    type: str
    default: >
             []
  workspace-names_locked:
    description:
      - >
        If set to true, locks the 'workspace-names' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.desktop.wm.preferences
  org_gnome_desktop_wm_preferences:
    mouse-button-modifier: "<Super>"
    mouse-button-modifier_locked: true
    resize-with-right-button: false
    resize-with-right-button_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'mouse-button-modifier': {
            'type': 'str',
            'default': "<Super>"
        },
        'resize-with-right-button': {
            'type': 'bool',
            'default': True
        },
        'button-layout': {
            'type': 'str',
            'default': "appmenu:close"
        },
        'focus-mode': {
            'type': 'str',
            'default': "click"
        },
        'focus-new-windows': {
            'type': 'str',
            'default': "smart"
        },
        'raise-on-click': {
            'type': 'bool',
            'default': True
        },
        'action-double-click-titlebar': {
            'type': 'str',
            'default': "toggle-maximize"
        },
        'action-middle-click-titlebar': {
            'type': 'str',
            'default': "none"
        },
        'action-right-click-titlebar': {
            'type': 'str',
            'default': "menu"
        },
        'auto-raise': {
            'type': 'bool',
            'default': True
        },
        'auto-raise-delay': {
            'type': 'int',
            'default': 500
        },
        'theme': {
            'type': 'str',
            'default': "Adwaita"
        },
        'titlebar-uses-system-font': {
            'type': 'bool',
            'default': True
        },
        'titlebar-font': {
            'type': 'str',
            'default': "Adwaita Sans Bold 11"
        },
        'num-workspaces': {
            'type': 'int',
            'default': 4
        },
        'audible-bell': {
            'type': 'bool',
            'default': True
        },
        'visual-bell': {
            'type': 'bool',
            'default': True
        },
        'visual-bell-type': {
            'type': 'str',
            'default': "fullscreen-flash"
        },
        'disable-workarounds': {
            'type': 'bool',
            'default': True
        },
        'workspace-names': {
            'type': 'str',
            'default': "[]"
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_desktop_wm_preferences")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_desktop_wm_preferences")

    schema_full_path = "/org/gnome/desktop/wm/preferences/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
