#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_TextEditor
short_description: Manages GNOME GSettings for org.gnome.TextEditor
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.TextEditor' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  auto-save-delay:
    description:
      - >
        Auto Save Delay
      - >
        The delay in seconds to wait before auto-saving a draft.
    type: str
    default: >
             3
  auto-save-delay_locked:
    description:
      - >
        If set to true, locks the 'auto-save-delay' key to prevent user modification.
    type: bool
    default: false
  style-variant:
    description:
      - >
        Style Variant
      - >
        Use the light or dark variant of the GTK theme and/or GtkSourceView style scheme.
    type: str
    default: >
             follow
  style-variant_locked:
    description:
      - >
        If set to true, locks the 'style-variant' key to prevent user modification.
    type: bool
    default: false
  indent-style:
    description:
      - >
        Indentation Style
      - >
        Whether the editor should insert multiple spaces characters instead of tabs.
    type: str
    default: >
             tab
  indent-style_locked:
    description:
      - >
        If set to true, locks the 'indent-style' key to prevent user modification.
    type: bool
    default: false
  auto-indent:
    description:
      - >
        Auto Indent
      - >
        Automatically indent new lines copying the previous line's indentation.
    type: bool
    default: true
  auto-indent_locked:
    description:
      - >
        If set to true, locks the 'auto-indent' key to prevent user modification.
    type: bool
    default: false
  tab-width:
    description:
      - >
        Tab Width
      - >
        The number of spaces represented by a tab.
    type: str
    default: >
             8
  tab-width_locked:
    description:
      - >
        If set to true, locks the 'tab-width' key to prevent user modification.
    type: bool
    default: false
  indent-width:
    description:
      - >
        Indent Width
      - >
        The number of spaces to indent or -1 to use tab-width.
    type: int
    default: -1
  indent-width_locked:
    description:
      - >
        If set to true, locks the 'indent-width' key to prevent user modification.
    type: bool
    default: false
  show-line-numbers:
    description:
      - >
        Show Line Numbers
      - >
        Whether line numbers should be displayed next to each line.
    type: bool
    default: false
  show-line-numbers_locked:
    description:
      - >
        If set to true, locks the 'show-line-numbers' key to prevent user modification.
    type: bool
    default: false
  show-right-margin:
    description:
      - >
        Show Right Margin
      - >
        Whether a margin line should be displayed on the right of the editor.
    type: bool
    default: false
  show-right-margin_locked:
    description:
      - >
        If set to true, locks the 'show-right-margin' key to prevent user modification.
    type: bool
    default: false
  right-margin-position:
    description:
      - >
        Right Margin Position
      - >
        The position in characters at which the right margin should be displayed.
    type: str
    default: >
             80
  right-margin-position_locked:
    description:
      - >
        If set to true, locks the 'right-margin-position' key to prevent user modification.
    type: bool
    default: false
  show-map:
    description:
      - >
        Show Overview Map
      - >
        If enabled, an overview map of the file will be displayed to the side of the editor.
    type: bool
    default: false
  show-map_locked:
    description:
      - >
        If set to true, locks the 'show-map' key to prevent user modification.
    type: bool
    default: false
  show-grid:
    description:
      - >
        Show Background Grid
      - >
        If enabled, a blueprint style grid is printed on the editor background.
    type: bool
    default: false
  show-grid_locked:
    description:
      - >
        If set to true, locks the 'show-grid' key to prevent user modification.
    type: bool
    default: false
  highlight-current-line:
    description:
      - >
        Highlight current line
      - >
        If enabled, the current line will be highlighted.
    type: bool
    default: false
  highlight-current-line_locked:
    description:
      - >
        If set to true, locks the 'highlight-current-line' key to prevent user modification.
    type: bool
    default: false
  wrap-text:
    description:
      - >
        Text Wrapping
      - >
        Whether text should be wrapped.
    type: bool
    default: true
  wrap-text_locked:
    description:
      - >
        If set to true, locks the 'wrap-text' key to prevent user modification.
    type: bool
    default: false
  use-system-font:
    description:
      - >
        Use System Font
      - >
        Whether the default system monospace font should be used.
    type: bool
    default: true
  use-system-font_locked:
    description:
      - >
        If set to true, locks the 'use-system-font' key to prevent user modification.
    type: bool
    default: false
  custom-font:
    description:
      - >
        Custom Font
      - >
        A custom font to use in the editor.
    type: str
    default: >
             Monospace 11
  custom-font_locked:
    description:
      - >
        If set to true, locks the 'custom-font' key to prevent user modification.
    type: bool
    default: false
  style-scheme:
    description:
      - >
        Style Scheme
      - >
        The style scheme to use by the editor. It may translate this into a dark format when available.
    type: str
    default: >
             Adwaita
  style-scheme_locked:
    description:
      - >
        If set to true, locks the 'style-scheme' key to prevent user modification.
    type: bool
    default: false
  discover-settings:
    description:
      - >
        Discover File Settings
      - >
        If enabled, then Text Editor will try to discover file settings from modelines, editorconfig, or per-language defaults.
    type: bool
    default: true
  discover-settings_locked:
    description:
      - >
        If set to true, locks the 'discover-settings' key to prevent user modification.
    type: bool
    default: false
  spellcheck:
    description:
      - >
        Automatically check spelling
      - >
        If enabled, then Text Editor will check spelling as you type.
    type: bool
    default: true
  spellcheck_locked:
    description:
      - >
        If set to true, locks the 'spellcheck' key to prevent user modification.
    type: bool
    default: false
  restore-session:
    description:
      - >
        Restore session
      - >
        When Text Editor is running, restore the previous session.
    type: bool
    default: true
  restore-session_locked:
    description:
      - >
        If set to true, locks the 'restore-session' key to prevent user modification.
    type: bool
    default: false
  recolor-window:
    description:
      - >
        Recolor Window
      - >
        Use the style-scheme to recolor the application window.
    type: bool
    default: true
  recolor-window_locked:
    description:
      - >
        If set to true, locks the 'recolor-window' key to prevent user modification.
    type: bool
    default: false
  keybindings:
    description:
      - >
        Keybindings
      - >
        The keybindings to use within Text Editor.
    type: str
    default: >
             default
  keybindings_locked:
    description:
      - >
        If set to true, locks the 'keybindings' key to prevent user modification.
    type: bool
    default: false
  last-save-directory:
    description:
      - >
        Last Save Directory
      - >
        The directory last used in a save or save-as dialog.
    type: str
    default: ""
  last-save-directory_locked:
    description:
      - >
        If set to true, locks the 'last-save-directory' key to prevent user modification.
    type: bool
    default: false
  draw-spaces:
    description:
      - >
        Draw Spaces
      - >
        The various types of spaces to draw in the editor.
    type: str
    default: >
             []
  draw-spaces_locked:
    description:
      - >
        If set to true, locks the 'draw-spaces' key to prevent user modification.
    type: bool
    default: false
  enable-snippets:
    description:
      - >
        Enable Snippets
      - >
        Enable the use of snippets registered with GtkSourceView from within the editor.
    type: bool
    default: false
  enable-snippets_locked:
    description:
      - >
        If set to true, locks the 'enable-snippets' key to prevent user modification.
    type: bool
    default: false
  line-height:
    description:
      - >
        Line Height
      - >
        The line height to use for the selected font.
    type: str
    default: >
             1.2
  line-height_locked:
    description:
      - >
        If set to true, locks the 'line-height' key to prevent user modification.
    type: bool
    default: false
  highlight-matching-brackets:
    description:
      - >
        Highlight Matching Brackets
      - >
        Highlight matching brackets and braces.
    type: bool
    default: true
  highlight-matching-brackets_locked:
    description:
      - >
        If set to true, locks the 'highlight-matching-brackets' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.TextEditor
  org_gnome_TextEditor:
    auto-save-delay: "3"
    auto-save-delay_locked: true
    style-variant: "follow"
    style-variant_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'auto-save-delay': {
            'type': 'str',
            'default': "3"
        },
        'style-variant': {
            'type': 'str',
            'default': "follow"
        },
        'indent-style': {
            'type': 'str',
            'default': "tab"
        },
        'auto-indent': {
            'type': 'bool',
            'default': True
        },
        'tab-width': {
            'type': 'str',
            'default': "8"
        },
        'indent-width': {
            'type': 'int',
            'default': -1
        },
        'show-line-numbers': {
            'type': 'bool',
            'default': True
        },
        'show-right-margin': {
            'type': 'bool',
            'default': True
        },
        'right-margin-position': {
            'type': 'str',
            'default': "80"
        },
        'show-map': {
            'type': 'bool',
            'default': True
        },
        'show-grid': {
            'type': 'bool',
            'default': True
        },
        'highlight-current-line': {
            'type': 'bool',
            'default': True
        },
        'wrap-text': {
            'type': 'bool',
            'default': True
        },
        'use-system-font': {
            'type': 'bool',
            'default': True
        },
        'custom-font': {
            'type': 'str',
            'default': "Monospace 11"
        },
        'style-scheme': {
            'type': 'str',
            'default': "Adwaita"
        },
        'discover-settings': {
            'type': 'bool',
            'default': True
        },
        'spellcheck': {
            'type': 'bool',
            'default': True
        },
        'restore-session': {
            'type': 'bool',
            'default': True
        },
        'recolor-window': {
            'type': 'bool',
            'default': True
        },
        'keybindings': {
            'type': 'str',
            'default': "default"
        },
        'last-save-directory': {
            'type': 'str',
            'default': ''
        },
        'draw-spaces': {
            'type': 'str',
            'default': "[]"
        },
        'enable-snippets': {
            'type': 'bool',
            'default': True
        },
        'line-height': {
            'type': 'str',
            'default': "1.2"
        },
        'highlight-matching-brackets': {
            'type': 'bool',
            'default': True
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_TextEditor")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_TextEditor")

    schema_full_path = "/org/gnome/TextEditor/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
