#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_mutter_wayland_keybindings
short_description: Manages GNOME GSettings for org.gnome.mutter.wayland.keybindings
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.mutter.wayland.keybindings' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  switch-to-session-1:
    description:
      - >
        Switch to VT 1
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F1']
  switch-to-session-1_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-1' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-2:
    description:
      - >
        Switch to VT 2
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F2']
  switch-to-session-2_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-2' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-3:
    description:
      - >
        Switch to VT 3
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F3']
  switch-to-session-3_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-3' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-4:
    description:
      - >
        Switch to VT 4
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F4']
  switch-to-session-4_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-4' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-5:
    description:
      - >
        Switch to VT 5
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F5']
  switch-to-session-5_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-5' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-6:
    description:
      - >
        Switch to VT 6
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F6']
  switch-to-session-6_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-6' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-7:
    description:
      - >
        Switch to VT 7
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F7']
  switch-to-session-7_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-7' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-8:
    description:
      - >
        Switch to VT 8
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F8']
  switch-to-session-8_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-8' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-9:
    description:
      - >
        Switch to VT 9
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F9']
  switch-to-session-9_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-9' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-10:
    description:
      - >
        Switch to VT 10
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F10']
  switch-to-session-10_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-10' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-11:
    description:
      - >
        Switch to VT 11
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F11']
  switch-to-session-11_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-11' key to prevent user modification.
    type: bool
    default: false
  switch-to-session-12:
    description:
      - >
        Switch to VT 12
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Primary><Alt>F12']
  switch-to-session-12_locked:
    description:
      - >
        If set to true, locks the 'switch-to-session-12' key to prevent user modification.
    type: bool
    default: false
  restore-shortcuts:
    description:
      - >
        Re-enable shortcuts
      - >
        Description - Schema Blank
    type: str
    default: >
             ['<Super>Escape']
  restore-shortcuts_locked:
    description:
      - >
        If set to true, locks the 'restore-shortcuts' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.mutter.wayland.keybindings
  org_gnome_mutter_wayland_keybindings:
    switch-to-session-1: "['<Primary><Alt>F1']"
    switch-to-session-1_locked: true
    switch-to-session-2: "['<Primary><Alt>F2']"
    switch-to-session-2_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'switch-to-session-1': {
            'type': 'str',
            'default': "["'<Primary><Alt>F1'"]"
        },
        'switch-to-session-2': {
            'type': 'str',
            'default': "["'<Primary><Alt>F2'"]"
        },
        'switch-to-session-3': {
            'type': 'str',
            'default': "["'<Primary><Alt>F3'"]"
        },
        'switch-to-session-4': {
            'type': 'str',
            'default': "["'<Primary><Alt>F4'"]"
        },
        'switch-to-session-5': {
            'type': 'str',
            'default': "["'<Primary><Alt>F5'"]"
        },
        'switch-to-session-6': {
            'type': 'str',
            'default': "["'<Primary><Alt>F6'"]"
        },
        'switch-to-session-7': {
            'type': 'str',
            'default': "["'<Primary><Alt>F7'"]"
        },
        'switch-to-session-8': {
            'type': 'str',
            'default': "["'<Primary><Alt>F8'"]"
        },
        'switch-to-session-9': {
            'type': 'str',
            'default': "["'<Primary><Alt>F9'"]"
        },
        'switch-to-session-10': {
            'type': 'str',
            'default': "["'<Primary><Alt>F10'"]"
        },
        'switch-to-session-11': {
            'type': 'str',
            'default': "["'<Primary><Alt>F11'"]"
        },
        'switch-to-session-12': {
            'type': 'str',
            'default': "["'<Primary><Alt>F12'"]"
        },
        'restore-shortcuts': {
            'type': 'str',
            'default': "["'<Super>Escape'"]"
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.mutter.wayland.keybindings")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.mutter.wayland.keybindings")

    schema_full_path = "/org/gnome/mutter/wayland/keybindings/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
