#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_Evince
short_description: Manages GNOME GSettings for org.gnome.Evince
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.Evince' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  override-restrictions:
    description:
      - >
        Override document restrictions
      - >
        Override document restrictions, like restriction to copy or to print.
    type: bool
    default: true
  override-restrictions_locked:
    description:
      - >
        If set to true, locks the 'override-restrictions' key to prevent user modification.
    type: bool
    default: false
  auto-reload:
    description:
      - >
        Automatically reload the document
      - >
        The document is automatically reloaded on file change.
    type: bool
    default: true
  auto-reload_locked:
    description:
      - >
        If set to true, locks the 'auto-reload' key to prevent user modification.
    type: bool
    default: false
  document-directory:
    description:
      - >
        The URI of the directory last used to open or save a document
      - >
        Description - Schema Blank
    type: str
    default: "nothing"
  document-directory_locked:
    description:
      - >
        If set to true, locks the 'document-directory' key to prevent user modification.
    type: bool
    default: false
  pictures-directory:
    description:
      - >
        The URI of the directory last used to save a picture
      - >
        Description - Schema Blank
    type: str
    default: "nothing"
  pictures-directory_locked:
    description:
      - >
        If set to true, locks the 'pictures-directory' key to prevent user modification.
    type: bool
    default: false
  page-cache-size:
    description:
      - >
        Page cache size in MiB
      - >
        The maximum size that will be used to cache rendered pages, limits maximum zoom level.
    type: str
    default: 50
  page-cache-size_locked:
    description:
      - >
        If set to true, locks the 'page-cache-size' key to prevent user modification.
    type: bool
    default: false
  show-caret-navigation-message:
    description:
      - >
        Show a dialog to confirm that the user wants to activate the caret navigation.
      - >
        Description - Schema Blank
    type: bool
    default: true
  show-caret-navigation-message_locked:
    description:
      - >
        If set to true, locks the 'show-caret-navigation-message' key to prevent user modification.
    type: bool
    default: false
  allow-links-change-zoom:
    description:
      - >
        Allow links to change the zoom level.
      - >
        Description - Schema Blank
    type: bool
    default: true
  allow-links-change-zoom_locked:
    description:
      - >
        If set to true, locks the 'allow-links-change-zoom' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.Evince
  org_gnome_Evince:
    override-restrictions: true
    override-restrictions_locked: true
    auto-reload: true
    auto-reload_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'override-restrictions': {
            'type': 'bool',
            'default': True
        },
        'auto-reload': {
            'type': 'bool',
            'default': True
        },
        'document-directory': {
            'type': 'str',
            'default': "nothing"
        },
        'pictures-directory': {
            'type': 'str',
            'default': "nothing"
        },
        'page-cache-size': {
            'type': 'str',
            'default': 50
        },
        'show-caret-navigation-message': {
            'type': 'bool',
            'default': True
        },
        'allow-links-change-zoom': {
            'type': 'bool',
            'default': True
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_Evince")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_Evince")

    schema_full_path = "/org/gnome/evince/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f"'{param_value}'"
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
