#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_terminal_legacy_profile
short_description: Manages GNOME GSettings for org.gnome.Terminal.Legacy.Profile
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.Terminal.Legacy.Profile' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  visible-name:
    description:
    - Human-readable name of the profile
    - Human-readable name of the profile.
    type: str
    default: Unnamed

  visible-name_locked:
    description:
    - >
      If set to true, locks the 'visible-name' key to prevent user modification.
    type: bool
    default: false
  foreground-color:
    description:
    - Default color of text in the terminal
    - Default color of text in the terminal, as a color specification (can be HTML-style
      hex digits, or a color name such as 'red').
    type: str
    default: '#171421'

  foreground-color_locked:
    description:
    - >
      If set to true, locks the 'foreground-color' key to prevent user modification.
    type: bool
    default: false
  background-color:
    description:
    - Default color of terminal background
    - Default color of terminal background, as a color specification (can be HTML-style
      hex digits, or a color name such as 'red').
    type: str
    default: '#ffffff'

  background-color_locked:
    description:
    - >
      If set to true, locks the 'background-color' key to prevent user modification.
    type: bool
    default: false
  bold-color:
    description:
    - Default color of bold text in the terminal
    - Default color of bold text in the terminal, as a color specification (can be HTML-style
      hex digits, or a color name such as 'red'). This is ignored if bold-color-same-as-fg
      is true.
    type: str
    default: '#000000'

  bold-color_locked:
    description:
    - >
      If set to true, locks the 'bold-color' key to prevent user modification.
    type: bool
    default: false
  bold-color-same-as-fg:
    description:
    - Whether bold text should use the same color as normal text
    - If true, boldface text will be rendered using the same color as normal text.
    type: bool
    default: true

  bold-color-same-as-fg_locked:
    description:
    - >
      If set to true, locks the 'bold-color-same-as-fg' key to prevent user modification.
    type: bool
    default: false
  cell-height-scale:
    description:
    - "Scale factor for the cell height to increase line spacing. (Does not increase the\
      \ font\u2019s height.)"
    - Description - Schema Blank
    type: float
    default: 1.0

  cell-height-scale_locked:
    description:
    - >
      If set to true, locks the 'cell-height-scale' key to prevent user modification.
    type: bool
    default: false
  cell-width-scale:
    description:
    - "Scale factor for the cell width to increase letter spacing. (Does not increase\
      \ the font\u2019s width.)"
    - Description - Schema Blank
    type: float
    default: 1.0

  cell-width-scale_locked:
    description:
    - >
      If set to true, locks the 'cell-width-scale' key to prevent user modification.
    type: bool
    default: false
  cursor-colors-set:
    description:
    - Whether to use custom cursor colors
    - If true, use the cursor colors from the profile.
    type: bool
    default: false

  cursor-colors-set_locked:
    description:
    - >
      If set to true, locks the 'cursor-colors-set' key to prevent user modification.
    type: bool
    default: false
  cursor-background-color:
    description:
    - Cursor background color
    - Custom color of the background of the terminal's cursor, as a color specification
      (can be HTML-style hex digits, or a color name such as 'red'). This is ignored if
      cursor-colors-set is false.
    type: str
    default: '#000000'

  cursor-background-color_locked:
    description:
    - >
      If set to true, locks the 'cursor-background-color' key to prevent user modification.
    type: bool
    default: false
  cursor-foreground-color:
    description:
    - Cursor foreground colour
    - Custom color for the foreground of the text character at the terminal's cursor position,
      as a color specification (can be HTML-style hex digits, or a color name such as
      'red'). This is ignored if cursor-colors-set is false.
    type: str
    default: '#ffffff'

  cursor-foreground-color_locked:
    description:
    - >
      If set to true, locks the 'cursor-foreground-color' key to prevent user modification.
    type: bool
    default: false
  highlight-colors-set:
    description:
    - Whether to use custom highlight colors
    - If true, use the highlight colors from the profile.
    type: bool
    default: false

  highlight-colors-set_locked:
    description:
    - >
      If set to true, locks the 'highlight-colors-set' key to prevent user modification.
    type: bool
    default: false
  highlight-background-color:
    description:
    - Highlight background color
    - Custom color of the background of the terminal's highlight, as a color specification
      (can be HTML-style hex digits, or a color name such as 'red'). This is ignored if
      highlight-colors-set is false.
    type: str
    default: '#000000'

  highlight-background-color_locked:
    description:
    - >
      If set to true, locks the 'highlight-background-color' key to prevent user modification.
    type: bool
    default: false
  highlight-foreground-color:
    description:
    - Highlight foreground colour
    - Custom color for the foreground of the text character at the terminal's highlight
      position, as a color specification (can be HTML-style hex digits, or a color name
      such as 'red'). This is ignored if highlight-colors-set is false.
    type: str
    default: '#ffffff'

  highlight-foreground-color_locked:
    description:
    - >
      If set to true, locks the 'highlight-foreground-color' key to prevent user modification.
    type: bool
    default: false
  enable-bidi:
    description:
    - Whether to perform bidirectional text rendering
    - If true, perform bidirectional text rendering ('BiDi').
    type: bool
    default: true

  enable-bidi_locked:
    description:
    - >
      If set to true, locks the 'enable-bidi' key to prevent user modification.
    type: bool
    default: false
  enable-shaping:
    description:
    - Whether to perform Arabic shaping
    - If true, shape Arabic text.
    type: bool
    default: true

  enable-shaping_locked:
    description:
    - >
      If set to true, locks the 'enable-shaping' key to prevent user modification.
    type: bool
    default: false
  enable-sixel:
    description:
    - Whether to enable SIXEL images
    - If true, SIXEL sequences are parsed and images are rendered.
    type: bool
    default: false

  enable-sixel_locked:
    description:
    - >
      If set to true, locks the 'enable-sixel' key to prevent user modification.
    type: bool
    default: false
  bold-is-bright:
    description:
    - Whether bold is also bright
    - If true, setting bold on the first 8 colors also switches to their bright variants.
    type: bool
    default: false

  bold-is-bright_locked:
    description:
    - >
      If set to true, locks the 'bold-is-bright' key to prevent user modification.
    type: bool
    default: false
  audible-bell:
    description:
    - Whether to ring the terminal bell
    - Description - Schema Blank
    type: bool
    default: true

  audible-bell_locked:
    description:
    - >
      If set to true, locks the 'audible-bell' key to prevent user modification.
    type: bool
    default: false
  word-char-exceptions:
    description:
    - List of punctuation characters that are treated as word characters
    - By default, when doing word-wise selection, most punctuation breaks up word boundaries.
      This list of exceptions will instead be treated as part of the word.
    type: str
    default: null

  word-char-exceptions_locked:
    description:
    - >
      If set to true, locks the 'word-char-exceptions' key to prevent user modification.
    type: bool
    default: false
  default-size-columns:
    description:
    - Default number of columns
    - Number of columns in newly created terminal windows. Has no effect if use_custom_default_size
      is not enabled.
    type: int
    default: 80

  default-size-columns_locked:
    description:
    - >
      If set to true, locks the 'default-size-columns' key to prevent user modification.
    type: bool
    default: false
  default-size-rows:
    description:
    - Default number of rows
    - Number of rows in newly created terminal windows. Has no effect if use_custom_default_size
      is not enabled.
    type: int
    default: 24

  default-size-rows_locked:
    description:
    - >
      If set to true, locks the 'default-size-rows' key to prevent user modification.
    type: bool
    default: false
  scrollbar-policy:
    description:
    - When to show the scrollbar
    - Description - Schema Blank
    type: str
    default: always

  scrollbar-policy_locked:
    description:
    - >
      If set to true, locks the 'scrollbar-policy' key to prevent user modification.
    type: bool
    default: false
  scrollback-lines:
    description:
    - Number of lines to keep in scrollback
    - Number of scrollback lines to keep around. You can scroll back in the terminal by
      this number of lines; lines that don't fit in the scrollback are discarded. If scrollback_unlimited
      is true, this value is ignored.
    type: int
    default: 10000

  scrollback-lines_locked:
    description:
    - >
      If set to true, locks the 'scrollback-lines' key to prevent user modification.
    type: bool
    default: false
  scrollback-unlimited:
    description:
    - Whether an unlimited number of lines should be kept in scrollback
    - If true, scrollback lines will never be discarded. The scrollback history is stored
      on disk temporarily, so this may cause the system to run out of disk space if there
      is a lot of output to the terminal.
    type: bool
    default: false

  scrollback-unlimited_locked:
    description:
    - >
      If set to true, locks the 'scrollback-unlimited' key to prevent user modification.
    type: bool
    default: false
  scroll-on-insert:
    description:
    - Whether to scroll to the bottom when text is inserted
    - If true, the terminal will scroll to the bottom when text is inserted by paste.
    type: bool
    default: true

  scroll-on-insert_locked:
    description:
    - >
      If set to true, locks the 'scroll-on-insert' key to prevent user modification.
    type: bool
    default: false
  scroll-on-keystroke:
    description:
    - Whether to scroll to the bottom when a key is pressed
    - If true, pressing a key jumps the scrollbar to the bottom.
    type: bool
    default: true

  scroll-on-keystroke_locked:
    description:
    - >
      If set to true, locks the 'scroll-on-keystroke' key to prevent user modification.
    type: bool
    default: false
  scroll-on-output:
    description:
    - "Whether to scroll to the bottom when there\u2019s new output"
    - If true, whenever there's new output the terminal will scroll to the bottom.
    type: bool
    default: false

  scroll-on-output_locked:
    description:
    - >
      If set to true, locks the 'scroll-on-output' key to prevent user modification.
    type: bool
    default: false
  exit-action:
    description:
    - What to do with the terminal when the child command exits
    - Possible values are 'close' to close the terminal, 'restart' to restart the command,
      and 'hold' to keep the terminal open with no command running inside.
    type: str
    default: close

  exit-action_locked:
    description:
    - >
      If set to true, locks the 'exit-action' key to prevent user modification.
    type: bool
    default: false
  login-shell:
    description:
    - Whether to launch the command in the terminal as a login shell
    - If true, the command inside the terminal will be launched as a login shell (argv[0]
      will have a hyphen in front of it).
    type: bool
    default: false

  login-shell_locked:
    description:
    - >
      If set to true, locks the 'login-shell' key to prevent user modification.
    type: bool
    default: false
  preserve-working-directory:
    description:
    - Whether to preserve the working directory when opening a new terminal
    - Controls when opening a new terminal from a previous one carries over the working
      directory of the opening terminal to the new one.
    type: str
    default: safe

  preserve-working-directory_locked:
    description:
    - >
      If set to true, locks the 'preserve-working-directory' key to prevent user modification.
    type: bool
    default: false
  use-custom-command:
    description:
    - Whether to run a custom command instead of the shell
    - If true, the value of the custom_command setting will be used in place of running
      a shell.
    type: bool
    default: false

  use-custom-command_locked:
    description:
    - >
      If set to true, locks the 'use-custom-command' key to prevent user modification.
    type: bool
    default: false
  cursor-blink-mode:
    description:
    - Whether to blink the cursor
    - The possible values are 'system' to use the global cursor blinking settings, or
      'on' or 'off' to set the mode explicitly.
    type: str
    default: system

  cursor-blink-mode_locked:
    description:
    - >
      If set to true, locks the 'cursor-blink-mode' key to prevent user modification.
    type: bool
    default: false
  cursor-shape:
    description:
    - The cursor appearance
    - Description - Schema Blank
    type: str
    default: block

  cursor-shape_locked:
    description:
    - >
      If set to true, locks the 'cursor-shape' key to prevent user modification.
    type: bool
    default: false
  text-blink-mode:
    description:
    - "Possible values are \u201Calways\u201D or \u201Cnever\u201D allow blinking text,\
      \ or only when the terminal is \u201Cfocused\u201D or \u201Cunfocused\u201D."
    - Description - Schema Blank
    type: str
    default: always

  text-blink-mode_locked:
    description:
    - >
      If set to true, locks the 'text-blink-mode' key to prevent user modification.
    type: bool
    default: false
  custom-command:
    description:
    - Custom command to use instead of the shell
    - Run this command in place of the shell, if use_custom_command is true.
    type: str
    default: ''

  custom-command_locked:
    description:
    - >
      If set to true, locks the 'custom-command' key to prevent user modification.
    type: bool
    default: false
  palette:
    description:
    - Palette for terminal applications
    - Description - Schema Blank
    type: str
    default:
    - '#171421'
    - '#c01c28'
    - '#26a269'
    - '#a2734c'
    - '#12488b'
    - '#a347ba'
    - '#2aa1b3'
    - '#d0cfcc'
    - '#5e5c64'
    - '#f66151'
    - '#33d17a'
    - '#e9ad0c'
    - '#2a7bde'
    - '#c061cb'
    - '#33c7de'
    - '#ffffff'

  palette_locked:
    description:
    - >
      If set to true, locks the 'palette' key to prevent user modification.
    type: bool
    default: false
  font:
    description:
    - A Pango font name and size
    - Description - Schema Blank
    type: str
    default: Monospace 12

  font_locked:
    description:
    - >
      If set to true, locks the 'font' key to prevent user modification.
    type: bool
    default: false
  backspace-binding:
    description:
    - The code sequence the Backspace key generates
    - Description - Schema Blank
    type: str
    default: ascii-delete

  backspace-binding_locked:
    description:
    - >
      If set to true, locks the 'backspace-binding' key to prevent user modification.
    type: bool
    default: false
  delete-binding:
    description:
    - The code sequence the Delete key generates
    - Description - Schema Blank
    type: str
    default: delete-sequence

  delete-binding_locked:
    description:
    - >
      If set to true, locks the 'delete-binding' key to prevent user modification.
    type: bool
    default: false
  use-theme-colors:
    description:
    - Whether to use the colors from the theme for the terminal widget
    - Description - Schema Blank
    type: bool
    default: true

  use-theme-colors_locked:
    description:
    - >
      If set to true, locks the 'use-theme-colors' key to prevent user modification.
    type: bool
    default: false
  use-system-font:
    description:
    - Whether to use the system monospace font
    - Description - Schema Blank
    type: bool
    default: true

  use-system-font_locked:
    description:
    - >
      If set to true, locks the 'use-system-font' key to prevent user modification.
    type: bool
    default: false
  rewrap-on-resize:
    description:
    - Whether to rewrap the terminal contents on window resize
    - Description - Schema Blank
    type: bool
    default: true

  rewrap-on-resize_locked:
    description:
    - >
      If set to true, locks the 'rewrap-on-resize' key to prevent user modification.
    type: bool
    default: false
  encoding:
    description:
    - Which encoding to use
    - Description - Schema Blank
    type: str
    default: UTF-8

  encoding_locked:
    description:
    - >
      If set to true, locks the 'encoding' key to prevent user modification.
    type: bool
    default: false
  cjk-utf8-ambiguous-width:
    description:
    - Whether ambiguous-width characters are narrow or wide when using UTF-8 encoding
    - Description - Schema Blank
    type: str
    default: narrow

  cjk-utf8-ambiguous-width_locked:
    description:
    - >
      If set to true, locks the 'cjk-utf8-ambiguous-width' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.Terminal.Legacy.Profile
  org_gnome_terminal_legacy_profile:
    visible-name: Unnamed

    foreground-color: '#171421'

    background-color: '#ffffff'

    bold-color: '#000000'

    bold-color-same-as-fg: true

    cell-height-scale: 1.0

    cell-width-scale: 1.0

    cursor-colors-set: false

    cursor-background-color: '#000000'

    cursor-foreground-color: '#ffffff'

    highlight-colors-set: false

    highlight-background-color: '#000000'

    highlight-foreground-color: '#ffffff'

    enable-bidi: true

    enable-shaping: true

    enable-sixel: false

    bold-is-bright: false

    audible-bell: true

    word-char-exceptions: null

    default-size-columns: 80

    default-size-rows: 24

    scrollbar-policy: always

    scrollback-lines: 10000

    scrollback-unlimited: false

    scroll-on-insert: true

    scroll-on-keystroke: true

    scroll-on-output: false

    exit-action: close

    login-shell: false

    preserve-working-directory: safe

    use-custom-command: false

    cursor-blink-mode: system

    cursor-shape: block

    text-blink-mode: always

    custom-command: ''

    palette:
    - '#171421'
    - '#c01c28'
    - '#26a269'
    - '#a2734c'
    - '#12488b'
    - '#a347ba'
    - '#2aa1b3'
    - '#d0cfcc'
    - '#5e5c64'
    - '#f66151'
    - '#33d17a'
    - '#e9ad0c'
    - '#2a7bde'
    - '#c061cb'
    - '#33c7de'
    - '#ffffff'

    font: Monospace 12

    backspace-binding: ascii-delete

    delete-binding: delete-sequence

    use-theme-colors: true

    use-system-font: true

    rewrap-on-resize: true

    encoding: UTF-8

    cjk-utf8-ambiguous-width: narrow

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'visible-name': {
            'default': 'Unnamed',
            'type': 'str',
            'gtype':'s',
        },
        'foreground-color': {
            'default': '#171421',
            'type': 'str',
            'gtype':'s',
        },
        'background-color': {
            'default': '#ffffff',
            'type': 'str',
            'gtype':'s',
        },
        'bold-color': {
            'default': '#000000',
            'type': 'str',
            'gtype':'s',
        },
        'bold-color-same-as-fg': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'cell-height-scale': {
            'default': 1.0,
            'type': 'float',
            'gtype':'d',
        },
        'cell-width-scale': {
            'default': 1.0,
            'type': 'float',
            'gtype':'d',
        },
        'cursor-colors-set': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'cursor-background-color': {
            'default': '#000000',
            'type': 'str',
            'gtype':'s',
        },
        'cursor-foreground-color': {
            'default': '#ffffff',
            'type': 'str',
            'gtype':'s',
        },
        'highlight-colors-set': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'highlight-background-color': {
            'default': '#000000',
            'type': 'str',
            'gtype':'s',
        },
        'highlight-foreground-color': {
            'default': '#ffffff',
            'type': 'str',
            'gtype':'s',
        },
        'enable-bidi': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'enable-shaping': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'enable-sixel': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'bold-is-bright': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'audible-bell': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'word-char-exceptions': {
            'default': None,
            'type': 'str',
            'gtype':'ms',
        },
        'default-size-columns': {
            'default': 80,
            'type': 'int',
            'gtype':'i',
        },
        'default-size-rows': {
            'default': 24,
            'type': 'int',
            'gtype':'i',
        },
        'scrollbar-policy': {
            'default': 'always',
            'type': 'str',
            'gtype':'s',
        },
        'scrollback-lines': {
            'default': 10000,
            'type': 'int',
            'gtype':'i',
        },
        'scrollback-unlimited': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'scroll-on-insert': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'scroll-on-keystroke': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'scroll-on-output': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'exit-action': {
            'default': 'close',
            'type': 'str',
            'gtype':'s',
        },
        'login-shell': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'preserve-working-directory': {
            'default': 'safe',
            'type': 'str',
            'gtype':'s',
        },
        'use-custom-command': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'cursor-blink-mode': {
            'default': 'system',
            'type': 'str',
            'gtype':'s',
        },
        'cursor-shape': {
            'default': 'block',
            'type': 'str',
            'gtype':'s',
        },
        'text-blink-mode': {
            'default': 'always',
            'type': 'str',
            'gtype':'s',
        },
        'custom-command': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'palette': {
            'default': ['#171421', '#c01c28', '#26a269', '#a2734c', '#12488b', '#a347ba', '#2aa1b3', '#d0cfcc', '#5e5c64', '#f66151', '#33d17a', '#e9ad0c', '#2a7bde', '#c061cb', '#33c7de', '#ffffff'],
            'type': 'str',
            'gtype':'as',
        },
        'font': {
            'default': 'Monospace 12',
            'type': 'str',
            'gtype':'s',
        },
        'backspace-binding': {
            'default': 'ascii-delete',
            'type': 'str',
            'gtype':'s',
        },
        'delete-binding': {
            'default': 'delete-sequence',
            'type': 'str',
            'gtype':'s',
        },
        'use-theme-colors': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'use-system-font': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'rewrap-on-resize': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'encoding': {
            'default': 'UTF-8',
            'type': 'str',
            'gtype':'s',
        },
        'cjk-utf8-ambiguous-width': {
            'default': 'narrow',
            'type': 'str',
            'gtype':'s',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.Terminal.Legacy.Profile")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.Terminal.Legacy.Profile")

    schema_full_path = "None"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
