#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_simplescan
short_description: Manages GNOME GSettings for org.gnome.SimpleScan
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.SimpleScan' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  selected-device:
    description:
    - Device to scan from
    - SANE device to acquire images from.
    type: str
    default: ''

  selected-device_locked:
    description:
    - >
      If set to true, locks the 'selected-device' key to prevent user modification.
    type: bool
    default: false
  document-type:
    description:
    - Type of document being scanned
    - Type of document being scanned. This setting decides on the scan resolution, colors
      and post-processing.
    type: str
    default: photo

  document-type_locked:
    description:
    - >
      If set to true, locks the 'document-type' key to prevent user modification.
    type: bool
    default: false
  paper-width:
    description:
    - Width of paper in tenths of a mm
    - The width of the paper in tenths of a mm (or 0 for automatic paper detection).
    type: int
    default: 0

  paper-width_locked:
    description:
    - >
      If set to true, locks the 'paper-width' key to prevent user modification.
    type: bool
    default: false
  paper-height:
    description:
    - Height of paper in tenths of a mm
    - The height of the paper in tenths of a mm (or 0 for automatic paper detection).
    type: int
    default: 0

  paper-height_locked:
    description:
    - >
      If set to true, locks the 'paper-height' key to prevent user modification.
    type: bool
    default: false
  brightness:
    description:
    - Brightness of scan
    - The brightness adjustment from -100 to 100 (0 being none).
    type: int
    default: 0

  brightness_locked:
    description:
    - >
      If set to true, locks the 'brightness' key to prevent user modification.
    type: bool
    default: false
  contrast:
    description:
    - Contrast of scan
    - The contrast adjustment from -100 to 100 (0 being none).
    type: int
    default: 0

  contrast_locked:
    description:
    - >
      If set to true, locks the 'contrast' key to prevent user modification.
    type: bool
    default: false
  text-dpi:
    description:
    - Resolution for text scans
    - The resolution in dots-per-inch to use when scanning text.
    type: int
    default: 150

  text-dpi_locked:
    description:
    - >
      If set to true, locks the 'text-dpi' key to prevent user modification.
    type: bool
    default: false
  photo-dpi:
    description:
    - Resolution for image scans
    - The resolution in dots-per-inch to use when scanning images.
    type: int
    default: 300

  photo-dpi_locked:
    description:
    - >
      If set to true, locks the 'photo-dpi' key to prevent user modification.
    type: bool
    default: false
  page-side:
    description:
    - Page side to scan
    - The page side to scan.
    type: str
    default: both

  page-side_locked:
    description:
    - >
      If set to true, locks the 'page-side' key to prevent user modification.
    type: bool
    default: false
  save-directory:
    description:
    - Directory to save files to
    - The directory to save files to.  Defaults to the documents directory if unset.
    type: str
    default: ''

  save-directory_locked:
    description:
    - >
      If set to true, locks the 'save-directory' key to prevent user modification.
    type: bool
    default: false
  save-format:
    description:
    - File format that is used for saving image files
    - 'MIME type that is used for saving image files. Examples of supported MIME types:
      image/jpeg, image/png, application/pdf'
    type: str
    default: application/pdf

  save-format_locked:
    description:
    - >
      If set to true, locks the 'save-format' key to prevent user modification.
    type: bool
    default: false
  jpeg-quality:
    description:
    - Quality value to use for JPEG compression
    - Quality value to use for JPEG compression.
    type: int
    default: 75

  jpeg-quality_locked:
    description:
    - >
      If set to true, locks the 'jpeg-quality' key to prevent user modification.
    type: bool
    default: false
  page-delay:
    description:
    - Delay in millisecond between pages
    - Delay in millisecond between pages.
    type: int
    default: 1000

  page-delay_locked:
    description:
    - >
      If set to true, locks the 'page-delay' key to prevent user modification.
    type: bool
    default: false
  postproc-enabled:
    description:
    - Whether or not postprocessing is enabled
    - Whether or not postprocessing is enabled.
    type: bool
    default: false

  postproc-enabled_locked:
    description:
    - >
      If set to true, locks the 'postproc-enabled' key to prevent user modification.
    type: bool
    default: false
  postproc-script:
    description:
    - The path to the postprocessing script
    - The path to the postprocessing script.
    type: str
    default: ''

  postproc-script_locked:
    description:
    - >
      If set to true, locks the 'postproc-script' key to prevent user modification.
    type: bool
    default: false
  postproc-arguments:
    description:
    - Additional arguments for the postprocessing script
    - Additional arguments for the postprocessing script.
    type: str
    default: ''

  postproc-arguments_locked:
    description:
    - >
      If set to true, locks the 'postproc-arguments' key to prevent user modification.
    type: bool
    default: false
  postproc-keep-original:
    description:
    - Whether or not to keep the original, unprocessed file
    - Whether or not to keep the original, unprocessed file. The '_orig' filename will
      be added to the filename immediately before the file extension.
    type: bool
    default: false

  postproc-keep-original_locked:
    description:
    - >
      If set to true, locks the 'postproc-keep-original' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.SimpleScan
  org_gnome_simplescan:
    selected-device: ''

    document-type: photo

    paper-width: 0

    paper-height: 0

    brightness: 0

    contrast: 0

    text-dpi: 150

    photo-dpi: 300

    page-side: both

    save-directory: ''

    save-format: application/pdf

    jpeg-quality: 75

    page-delay: 1000

    postproc-enabled: false

    postproc-script: ''

    postproc-arguments: ''

    postproc-keep-original: false

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'selected-device': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'document-type': {
            'default': 'photo',
            'type': 'str',
            'gtype':'s',
        },
        'paper-width': {
            'default': 0,
            'type': 'int',
            'gtype':'i',
        },
        'paper-height': {
            'default': 0,
            'type': 'int',
            'gtype':'i',
        },
        'brightness': {
            'default': 0,
            'type': 'int',
            'gtype':'i',
        },
        'contrast': {
            'default': 0,
            'type': 'int',
            'gtype':'i',
        },
        'text-dpi': {
            'default': 150,
            'type': 'int',
            'gtype':'i',
        },
        'photo-dpi': {
            'default': 300,
            'type': 'int',
            'gtype':'i',
        },
        'page-side': {
            'default': 'both',
            'type': 'str',
            'gtype':'s',
        },
        'save-directory': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'save-format': {
            'default': 'application/pdf',
            'type': 'str',
            'gtype':'s',
        },
        'jpeg-quality': {
            'default': 75,
            'type': 'int',
            'gtype':'i',
        },
        'page-delay': {
            'default': 1000,
            'type': 'int',
            'gtype':'i',
        },
        'postproc-enabled': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'postproc-script': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'postproc-arguments': {
            'default': '',
            'type': 'str',
            'gtype':'s',
        },
        'postproc-keep-original': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.SimpleScan")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.SimpleScan")

    schema_full_path = "/org/gnome/simple-scan/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
