#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_freedesktop_tracker3_miner_files
short_description: Manages GNOME GSettings for org.freedesktop.Tracker3.Miner.Files
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.freedesktop.Tracker3.Miner.Files' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  initial-sleep:
    description:
    - Initial sleep
    - Initial sleep time, in seconds.
    type: int
    default: 15

  initial-sleep_locked:
    description:
    - >
      If set to true, locks the 'initial-sleep' key to prevent user modification.
    type: bool
    default: false
  throttle:
    description:
    - Throttle
    - Indexing speed, the higher the slower.
    type: int
    default: 0

  throttle_locked:
    description:
    - >
      If set to true, locks the 'throttle' key to prevent user modification.
    type: bool
    default: false
  low-disk-space-limit:
    description:
    - Low disk space limit
    - Disk space threshold in percent at which to pause indexing, or -1 to disable.
    type: int
    default: -1

  low-disk-space-limit_locked:
    description:
    - >
      If set to true, locks the 'low-disk-space-limit' key to prevent user modification.
    type: bool
    default: false
  crawling-interval:
    description:
    - Crawling interval
    - "Interval in days to check whether the filesystem is up to date in the database.\n\
      \t0 forces crawling anytime, -1 forces it only after unclean shutdowns, and -2\n\
      \tdisables it entirely."
    type: int
    default: -1

  crawling-interval_locked:
    description:
    - >
      If set to true, locks the 'crawling-interval' key to prevent user modification.
    type: bool
    default: false
  removable-days-threshold:
    description:
    - "Removable devices\u2019 data permanence threshold"
    - "Threshold in days after which files from removables devices\n\twill be removed\
      \ from database if not mounted. 0 means never,\n\tmaximum is 365."
    type: int
    default: 3

  removable-days-threshold_locked:
    description:
    - >
      If set to true, locks the 'removable-days-threshold' key to prevent user modification.
    type: bool
    default: false
  enable-monitors:
    description:
    - Enable monitors
    - Set to false to completely disable any file monitoring
    type: bool
    default: true

  enable-monitors_locked:
    description:
    - >
      If set to true, locks the 'enable-monitors' key to prevent user modification.
    type: bool
    default: false
  index-removable-devices:
    description:
    - Index removable devices
    - Set to true to enable indexing mounted directories for removable devices.
    type: bool
    default: false

  index-removable-devices_locked:
    description:
    - >
      If set to true, locks the 'index-removable-devices' key to prevent user modification.
    type: bool
    default: false
  index-optical-discs:
    description:
    - Index optical discs
    - "Set to true to enable indexing CDs, DVDs, and generally optical media\n\t(if removable\
      \ devices are not indexed, optical discs won't be either)"
    type: bool
    default: false

  index-optical-discs_locked:
    description:
    - >
      If set to true, locks the 'index-optical-discs' key to prevent user modification.
    type: bool
    default: false
  index-on-battery:
    description:
    - Index when running on battery
    - Set to true to index while running on battery
    type: bool
    default: true

  index-on-battery_locked:
    description:
    - >
      If set to true, locks the 'index-on-battery' key to prevent user modification.
    type: bool
    default: false
  index-on-battery-first-time:
    description:
    - Perform initial indexing when running on battery
    - Set to true to index while running on battery for the first time only
    type: bool
    default: true

  index-on-battery-first-time_locked:
    description:
    - >
      If set to true, locks the 'index-on-battery-first-time' key to prevent user modification.
    type: bool
    default: false
  index-recursive-directories:
    description:
    - Directories to index recursively
    - "List of directories to index recursively, Special values include:\n\t\u2018&DESKTOP',\
      \ \u2018&DOCUMENTS', \u2018&DOWNLOAD', \u2018&MUSIC', \u2018&PICTURES',\n\t\u2018\
      &PUBLIC_SHARE', \u2018&TEMPLATES', \u2018&VIDEOS'.\n\n\tSee /etc/xdg/user-dirs.defaults\
      \ and $HOME/.config/user-dirs.default"
    type: str
    default:
    - '&DESKTOP'
    - '&DOCUMENTS'
    - '&MUSIC'
    - '&PICTURES'
    - '&VIDEOS'

  index-recursive-directories_locked:
    description:
    - >
      If set to true, locks the 'index-recursive-directories' key to prevent user modification.
    type: bool
    default: false
  index-single-directories:
    description:
    - Directories to index non-recursively
    - "List of directories to index without inspecting subfolders, Special values include:\n\
      \t\u2018&DESKTOP', \u2018&DOCUMENTS', \u2018&DOWNLOAD', \u2018&MUSIC', \u2018&PICTURES',\n\
      \t\u2018&PUBLIC_SHARE', \u2018&TEMPLATES', \u2018&VIDEOS'.\n\n\tSee /etc/xdg/user-dirs.defaults\
      \ and $HOME/.config/user-dirs.default"
    type: str
    default:
    - $HOME
    - '&DOWNLOAD'

  index-single-directories_locked:
    description:
    - >
      If set to true, locks the 'index-single-directories' key to prevent user modification.
    type: bool
    default: false
  ignored-files:
    description:
    - Ignored files
    - List of file patterns to avoid
    type: str
    default:
    - '*~'
    - '*.o'
    - '*.la'
    - '*.lo'
    - '*.loT'
    - '*.in'
    - '*.m4'
    - '*.rej'
    - '*.gmo'
    - '*.orig'
    - '*.pc'
    - '*.omf'
    - '*.aux'
    - '*.tmp'
    - '*.vmdk'
    - '*.vm*'
    - '*.nvram'
    - '*.part'
    - '*.rcore'
    - '*.lzo'
    - autom4te
    - conftest
    - confstat
    - Makefile
    - SCCS
    - ltmain.sh
    - libtool
    - config.status
    - confdefs.h
    - configure
    - '#*#'
    - ~$*.doc?
    - ~$*.dot?
    - ~$*.xls?
    - ~$*.xlt?
    - ~$*.xlam
    - ~$*.ppt?
    - ~$*.pot?
    - ~$*.ppam
    - ~$*.ppsm
    - ~$*.ppsx
    - ~$*.vsd?
    - ~$*.vss?
    - ~$*.vst?
    - '*.directory'

  ignored-files_locked:
    description:
    - >
      If set to true, locks the 'ignored-files' key to prevent user modification.
    type: bool
    default: false
  ignored-directories:
    description:
    - Ignored directories
    - List of directories to avoid
    type: str
    default:
    - po
    - CVS
    - core-dumps
    - lost+found

  ignored-directories_locked:
    description:
    - >
      If set to true, locks the 'ignored-directories' key to prevent user modification.
    type: bool
    default: false
  ignored-directories-with-content:
    description:
    - Ignored directories with content
    - Avoid any directory containing a file blocklisted here
    type: str
    default:
    - .trackerignore
    - .git
    - .hg
    - .nomedia

  ignored-directories-with-content_locked:
    description:
    - >
      If set to true, locks the 'ignored-directories-with-content' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.freedesktop.Tracker3.Miner.Files
  org_freedesktop_tracker3_miner_files:
    initial-sleep: 15

    throttle: 0

    low-disk-space-limit: -1

    crawling-interval: -1

    removable-days-threshold: 3

    enable-monitors: true

    index-removable-devices: false

    index-optical-discs: false

    index-on-battery: true

    index-on-battery-first-time: true

    index-recursive-directories:
    - '&DESKTOP'
    - '&DOCUMENTS'
    - '&MUSIC'
    - '&PICTURES'
    - '&VIDEOS'

    index-single-directories:
    - $HOME
    - '&DOWNLOAD'

    ignored-files:
    - '*~'
    - '*.o'
    - '*.la'
    - '*.lo'
    - '*.loT'
    - '*.in'
    - '*.m4'
    - '*.rej'
    - '*.gmo'
    - '*.orig'
    - '*.pc'
    - '*.omf'
    - '*.aux'
    - '*.tmp'
    - '*.vmdk'
    - '*.vm*'
    - '*.nvram'
    - '*.part'
    - '*.rcore'
    - '*.lzo'
    - autom4te
    - conftest
    - confstat
    - Makefile
    - SCCS
    - ltmain.sh
    - libtool
    - config.status
    - confdefs.h
    - configure
    - '#*#'
    - ~$*.doc?
    - ~$*.dot?
    - ~$*.xls?
    - ~$*.xlt?
    - ~$*.xlam
    - ~$*.ppt?
    - ~$*.pot?
    - ~$*.ppam
    - ~$*.ppsm
    - ~$*.ppsx
    - ~$*.vsd?
    - ~$*.vss?
    - ~$*.vst?
    - '*.directory'

    ignored-directories:
    - po
    - CVS
    - core-dumps
    - lost+found

    ignored-directories-with-content:
    - .trackerignore
    - .git
    - .hg
    - .nomedia

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'initial-sleep': {
            'default': 15,
            'type': 'int',
            'gtype':'i',
        },
        'throttle': {
            'default': 0,
            'type': 'int',
            'gtype':'i',
        },
        'low-disk-space-limit': {
            'default': -1,
            'type': 'int',
            'gtype':'i',
        },
        'crawling-interval': {
            'default': -1,
            'type': 'int',
            'gtype':'i',
        },
        'removable-days-threshold': {
            'default': 3,
            'type': 'int',
            'gtype':'i',
        },
        'enable-monitors': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'index-removable-devices': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'index-optical-discs': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'index-on-battery': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'index-on-battery-first-time': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
        'index-recursive-directories': {
            'default': ['&DESKTOP', '&DOCUMENTS', '&MUSIC', '&PICTURES', '&VIDEOS'],
            'type': 'str',
            'gtype':'as',
        },
        'index-single-directories': {
            'default': ['$HOME', '&DOWNLOAD'],
            'type': 'str',
            'gtype':'as',
        },
        'ignored-files': {
            'default': ['*~', '*.o', '*.la', '*.lo', '*.loT', '*.in', '*.m4', '*.rej', '*.gmo', '*.orig', '*.pc', '*.omf', '*.aux', '*.tmp', '*.vmdk', '*.vm*', '*.nvram', '*.part', '*.rcore', '*.lzo', 'autom4te', 'conftest', 'confstat', 'Makefile', 'SCCS', 'ltmain.sh', 'libtool', 'config.status', 'confdefs.h', 'configure', '#*#', '~$*.doc?', '~$*.dot?', '~$*.xls?', '~$*.xlt?', '~$*.xlam', '~$*.ppt?', '~$*.pot?', '~$*.ppam', '~$*.ppsm', '~$*.ppsx', '~$*.vsd?', '~$*.vss?', '~$*.vst?', '*.directory'],
            'type': 'str',
            'gtype':'as',
        },
        'ignored-directories': {
            'default': ['po', 'CVS', 'core-dumps', 'lost+found'],
            'type': 'str',
            'gtype':'as',
        },
        'ignored-directories-with-content': {
            'default': ['.trackerignore', '.git', '.hg', '.nomedia'],
            'type': 'str',
            'gtype':'as',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.freedesktop.Tracker3.Miner.Files")
    lock_file_path = os.path.join(locks_dir, "ansible-org.freedesktop.Tracker3.Miner.Files")

    schema_full_path = "/org/freedesktop/tracker/miner/files/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
