#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from pygvariant import GVariantSerializer, GVariantValueConverter
from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_desktop_wm_keybindings
short_description: Manages GNOME GSettings for org.gnome.desktop.wm.keybindings
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.desktop.wm.keybindings' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  switch-to-workspace-1:
    description:
    - Switch to workspace 1
    - Description - Schema Blank
    type: str
    default:
    - SuperHome

  switch-to-workspace-1_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-1' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-2:
    description:
    - Switch to workspace 2
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-2_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-2' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-3:
    description:
    - Switch to workspace 3
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-3_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-3' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-4:
    description:
    - Switch to workspace 4
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-4_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-4' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-5:
    description:
    - Switch to workspace 5
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-5_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-5' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-6:
    description:
    - Switch to workspace 6
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-6_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-6' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-7:
    description:
    - Switch to workspace 7
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-7_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-7' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-8:
    description:
    - Switch to workspace 8
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-8_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-8' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-9:
    description:
    - Switch to workspace 9
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-9_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-9' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-10:
    description:
    - Switch to workspace 10
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-10_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-10' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-11:
    description:
    - Switch to workspace 11
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-11_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-11' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-12:
    description:
    - Switch to workspace 12
    - Description - Schema Blank
    type: str
    default: []

  switch-to-workspace-12_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-12' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-left:
    description:
    - Switch to workspace left
    - Description - Schema Blank
    type: str
    default:
    - SuperPage_Up
    - SuperAltLeft
    - ControlAltLeft

  switch-to-workspace-left_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-left' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-right:
    description:
    - Switch to workspace right
    - Description - Schema Blank
    type: str
    default:
    - SuperPage_Down
    - SuperAltRight
    - ControlAltRight

  switch-to-workspace-right_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-right' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-up:
    description:
    - Switch to workspace above
    - Description - Schema Blank
    type: str
    default:
    - ControlAltUp

  switch-to-workspace-up_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-up' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-down:
    description:
    - Switch to workspace below
    - Description - Schema Blank
    type: str
    default:
    - ControlAltDown

  switch-to-workspace-down_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-down' key to prevent user modification.
    type: bool
    default: false
  switch-to-workspace-last:
    description:
    - Switch to last workspace
    - Description - Schema Blank
    type: str
    default:
    - SuperEnd

  switch-to-workspace-last_locked:
    description:
    - >
      If set to true, locks the 'switch-to-workspace-last' key to prevent user modification.
    type: bool
    default: false
  switch-group:
    description:
    - Switch windows of an application
    - Description - Schema Blank
    type: str
    default:
    - SuperAbove_Tab
    - AltAbove_Tab

  switch-group_locked:
    description:
    - >
      If set to true, locks the 'switch-group' key to prevent user modification.
    type: bool
    default: false
  switch-group-backward:
    description:
    - Reverse switch windows of an application
    - Description - Schema Blank
    type: str
    default:
    - ShiftSuperAbove_Tab
    - ShiftAltAbove_Tab

  switch-group-backward_locked:
    description:
    - >
      If set to true, locks the 'switch-group-backward' key to prevent user modification.
    type: bool
    default: false
  switch-applications:
    description:
    - Switch applications
    - Description - Schema Blank
    type: str
    default:
    - SuperTab
    - AltTab

  switch-applications_locked:
    description:
    - >
      If set to true, locks the 'switch-applications' key to prevent user modification.
    type: bool
    default: false
  switch-applications-backward:
    description:
    - Reverse switch applications
    - Description - Schema Blank
    type: str
    default:
    - ShiftSuperTab
    - ShiftAltTab

  switch-applications-backward_locked:
    description:
    - >
      If set to true, locks the 'switch-applications-backward' key to prevent user modification.
    type: bool
    default: false
  switch-windows:
    description:
    - Switch windows
    - Description - Schema Blank
    type: str
    default: []

  switch-windows_locked:
    description:
    - >
      If set to true, locks the 'switch-windows' key to prevent user modification.
    type: bool
    default: false
  switch-windows-backward:
    description:
    - Reverse switch windows
    - Description - Schema Blank
    type: str
    default: []

  switch-windows-backward_locked:
    description:
    - >
      If set to true, locks the 'switch-windows-backward' key to prevent user modification.
    type: bool
    default: false
  switch-panels:
    description:
    - Switch system controls
    - Description - Schema Blank
    type: str
    default:
    - ControlAltTab

  switch-panels_locked:
    description:
    - >
      If set to true, locks the 'switch-panels' key to prevent user modification.
    type: bool
    default: false
  switch-panels-backward:
    description:
    - Reverse switch system controls
    - Description - Schema Blank
    type: str
    default:
    - ShiftControlAltTab

  switch-panels-backward_locked:
    description:
    - >
      If set to true, locks the 'switch-panels-backward' key to prevent user modification.
    type: bool
    default: false
  cycle-group:
    description:
    - Switch windows of an app directly
    - Description - Schema Blank
    type: str
    default:
    - AltF6

  cycle-group_locked:
    description:
    - >
      If set to true, locks the 'cycle-group' key to prevent user modification.
    type: bool
    default: false
  cycle-group-backward:
    description:
    - Reverse switch windows of an app directly
    - Description - Schema Blank
    type: str
    default:
    - ShiftAltF6

  cycle-group-backward_locked:
    description:
    - >
      If set to true, locks the 'cycle-group-backward' key to prevent user modification.
    type: bool
    default: false
  cycle-windows:
    description:
    - Switch windows directly
    - Description - Schema Blank
    type: str
    default:
    - AltEscape

  cycle-windows_locked:
    description:
    - >
      If set to true, locks the 'cycle-windows' key to prevent user modification.
    type: bool
    default: false
  cycle-windows-backward:
    description:
    - Reverse switch windows directly
    - Description - Schema Blank
    type: str
    default:
    - ShiftAltEscape

  cycle-windows-backward_locked:
    description:
    - >
      If set to true, locks the 'cycle-windows-backward' key to prevent user modification.
    type: bool
    default: false
  cycle-panels:
    description:
    - Switch system controls directly
    - Description - Schema Blank
    type: str
    default:
    - ControlAltEscape

  cycle-panels_locked:
    description:
    - >
      If set to true, locks the 'cycle-panels' key to prevent user modification.
    type: bool
    default: false
  cycle-panels-backward:
    description:
    - Reverse switch system controls directly
    - Description - Schema Blank
    type: str
    default:
    - ShiftControlAltEscape

  cycle-panels-backward_locked:
    description:
    - >
      If set to true, locks the 'cycle-panels-backward' key to prevent user modification.
    type: bool
    default: false
  show-desktop:
    description:
    - Hide all normal windows
    - Description - Schema Blank
    type: str
    default: []

  show-desktop_locked:
    description:
    - >
      If set to true, locks the 'show-desktop' key to prevent user modification.
    type: bool
    default: false
  panel-main-menu:
    description:
    - 'DEPRECATED: This key is deprecated and ignored.'
    - Description - Schema Blank
    type: str
    default: []

  panel-main-menu_locked:
    description:
    - >
      If set to true, locks the 'panel-main-menu' key to prevent user modification.
    type: bool
    default: false
  panel-run-dialog:
    description:
    - Show the run command prompt
    - Description - Schema Blank
    type: str
    default:
    - AltF2

  panel-run-dialog_locked:
    description:
    - >
      If set to true, locks the 'panel-run-dialog' key to prevent user modification.
    type: bool
    default: false
  set-spew-mark:
    description:
    - "Don\u2019t use"
    - Description - Schema Blank
    type: str
    default: []

  set-spew-mark_locked:
    description:
    - >
      If set to true, locks the 'set-spew-mark' key to prevent user modification.
    type: bool
    default: false
  activate-window-menu:
    description:
    - Activate the window menu
    - Description - Schema Blank
    type: str
    default:
    - Altspace

  activate-window-menu_locked:
    description:
    - >
      If set to true, locks the 'activate-window-menu' key to prevent user modification.
    type: bool
    default: false
  toggle-fullscreen:
    description:
    - Toggle fullscreen mode
    - Description - Schema Blank
    type: str
    default: []

  toggle-fullscreen_locked:
    description:
    - >
      If set to true, locks the 'toggle-fullscreen' key to prevent user modification.
    type: bool
    default: false
  toggle-maximized:
    description:
    - Toggle maximization state
    - Description - Schema Blank
    type: str
    default:
    - AltF10

  toggle-maximized_locked:
    description:
    - >
      If set to true, locks the 'toggle-maximized' key to prevent user modification.
    type: bool
    default: false
  toggle-above:
    description:
    - Toggle window always appearing on top
    - Description - Schema Blank
    type: str
    default: []

  toggle-above_locked:
    description:
    - >
      If set to true, locks the 'toggle-above' key to prevent user modification.
    type: bool
    default: false
  maximize:
    description:
    - Maximize window
    - Description - Schema Blank
    type: str
    default:
    - SuperUp

  maximize_locked:
    description:
    - >
      If set to true, locks the 'maximize' key to prevent user modification.
    type: bool
    default: false
  unmaximize:
    description:
    - Restore window
    - Description - Schema Blank
    type: str
    default:
    - SuperDown
    - AltF5

  unmaximize_locked:
    description:
    - >
      If set to true, locks the 'unmaximize' key to prevent user modification.
    type: bool
    default: false
  minimize:
    description:
    - Minimize window
    - Description - Schema Blank
    type: str
    default:
    - Superh

  minimize_locked:
    description:
    - >
      If set to true, locks the 'minimize' key to prevent user modification.
    type: bool
    default: false
  close:
    description:
    - Close window
    - Description - Schema Blank
    type: str
    default:
    - AltF4

  close_locked:
    description:
    - >
      If set to true, locks the 'close' key to prevent user modification.
    type: bool
    default: false
  begin-move:
    description:
    - Move window
    - Description - Schema Blank
    type: str
    default:
    - AltF7

  begin-move_locked:
    description:
    - >
      If set to true, locks the 'begin-move' key to prevent user modification.
    type: bool
    default: false
  begin-resize:
    description:
    - Resize window
    - Description - Schema Blank
    type: str
    default:
    - AltF8

  begin-resize_locked:
    description:
    - >
      If set to true, locks the 'begin-resize' key to prevent user modification.
    type: bool
    default: false
  toggle-on-all-workspaces:
    description:
    - Toggle window on all workspaces or one
    - Description - Schema Blank
    type: str
    default: []

  toggle-on-all-workspaces_locked:
    description:
    - >
      If set to true, locks the 'toggle-on-all-workspaces' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-1:
    description:
    - Move window to workspace 1
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftHome

  move-to-workspace-1_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-1' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-2:
    description:
    - Move window to workspace 2
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-2_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-2' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-3:
    description:
    - Move window to workspace 3
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-3_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-3' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-4:
    description:
    - Move window to workspace 4
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-4_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-4' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-5:
    description:
    - Move window to workspace 5
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-5_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-5' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-6:
    description:
    - Move window to workspace 6
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-6_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-6' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-7:
    description:
    - Move window to workspace 7
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-7_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-7' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-8:
    description:
    - Move window to workspace 8
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-8_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-8' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-9:
    description:
    - Move window to workspace 9
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-9_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-9' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-10:
    description:
    - Move window to workspace 10
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-10_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-10' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-11:
    description:
    - Move window to workspace 11
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-11_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-11' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-12:
    description:
    - Move window to workspace 12
    - Description - Schema Blank
    type: str
    default: []

  move-to-workspace-12_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-12' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-last:
    description:
    - Move window to last workspace
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftEnd

  move-to-workspace-last_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-last' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-left:
    description:
    - Move window one workspace to the left
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftPage_Up
    - SuperShiftAltLeft
    - ControlShiftAltLeft

  move-to-workspace-left_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-left' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-right:
    description:
    - Move window one workspace to the right
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftPage_Down
    - SuperShiftAltRight
    - ControlShiftAltRight

  move-to-workspace-right_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-right' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-up:
    description:
    - Move window one workspace up
    - Description - Schema Blank
    type: str
    default:
    - ControlShiftAltUp

  move-to-workspace-up_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-up' key to prevent user modification.
    type: bool
    default: false
  move-to-workspace-down:
    description:
    - Move window one workspace down
    - Description - Schema Blank
    type: str
    default:
    - ControlShiftAltDown

  move-to-workspace-down_locked:
    description:
    - >
      If set to true, locks the 'move-to-workspace-down' key to prevent user modification.
    type: bool
    default: false
  move-to-monitor-left:
    description:
    - Move window to the next monitor on the left
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftLeft

  move-to-monitor-left_locked:
    description:
    - >
      If set to true, locks the 'move-to-monitor-left' key to prevent user modification.
    type: bool
    default: false
  move-to-monitor-right:
    description:
    - Move window to the next monitor on the right
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftRight

  move-to-monitor-right_locked:
    description:
    - >
      If set to true, locks the 'move-to-monitor-right' key to prevent user modification.
    type: bool
    default: false
  move-to-monitor-up:
    description:
    - Move window to the next monitor above
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftUp

  move-to-monitor-up_locked:
    description:
    - >
      If set to true, locks the 'move-to-monitor-up' key to prevent user modification.
    type: bool
    default: false
  move-to-monitor-down:
    description:
    - Move window to the next monitor below
    - Description - Schema Blank
    type: str
    default:
    - SuperShiftDown

  move-to-monitor-down_locked:
    description:
    - >
      If set to true, locks the 'move-to-monitor-down' key to prevent user modification.
    type: bool
    default: false
  raise-or-lower:
    description:
    - Raise window if covered, otherwise lower it
    - Description - Schema Blank
    type: str
    default: []

  raise-or-lower_locked:
    description:
    - >
      If set to true, locks the 'raise-or-lower' key to prevent user modification.
    type: bool
    default: false
  raise:
    description:
    - Raise window above other windows
    - Description - Schema Blank
    type: str
    default: []

  raise_locked:
    description:
    - >
      If set to true, locks the 'raise' key to prevent user modification.
    type: bool
    default: false
  lower:
    description:
    - Lower window below other windows
    - Description - Schema Blank
    type: str
    default: []

  lower_locked:
    description:
    - >
      If set to true, locks the 'lower' key to prevent user modification.
    type: bool
    default: false
  maximize-vertically:
    description:
    - Maximize window vertically
    - Description - Schema Blank
    type: str
    default: []

  maximize-vertically_locked:
    description:
    - >
      If set to true, locks the 'maximize-vertically' key to prevent user modification.
    type: bool
    default: false
  maximize-horizontally:
    description:
    - Maximize window horizontally
    - Description - Schema Blank
    type: str
    default: []

  maximize-horizontally_locked:
    description:
    - >
      If set to true, locks the 'maximize-horizontally' key to prevent user modification.
    type: bool
    default: false
  move-to-corner-nw:
    description:
    - Move window to top left corner
    - Description - Schema Blank
    type: str
    default: []

  move-to-corner-nw_locked:
    description:
    - >
      If set to true, locks the 'move-to-corner-nw' key to prevent user modification.
    type: bool
    default: false
  move-to-corner-ne:
    description:
    - Move window to top right corner
    - Description - Schema Blank
    type: str
    default: []

  move-to-corner-ne_locked:
    description:
    - >
      If set to true, locks the 'move-to-corner-ne' key to prevent user modification.
    type: bool
    default: false
  move-to-corner-sw:
    description:
    - Move window to bottom left corner
    - Description - Schema Blank
    type: str
    default: []

  move-to-corner-sw_locked:
    description:
    - >
      If set to true, locks the 'move-to-corner-sw' key to prevent user modification.
    type: bool
    default: false
  move-to-corner-se:
    description:
    - Move window to bottom right corner
    - Description - Schema Blank
    type: str
    default: []

  move-to-corner-se_locked:
    description:
    - >
      If set to true, locks the 'move-to-corner-se' key to prevent user modification.
    type: bool
    default: false
  move-to-side-n:
    description:
    - Move window to top edge of screen
    - Description - Schema Blank
    type: str
    default: []

  move-to-side-n_locked:
    description:
    - >
      If set to true, locks the 'move-to-side-n' key to prevent user modification.
    type: bool
    default: false
  move-to-side-s:
    description:
    - Move window to bottom edge of screen
    - Description - Schema Blank
    type: str
    default: []

  move-to-side-s_locked:
    description:
    - >
      If set to true, locks the 'move-to-side-s' key to prevent user modification.
    type: bool
    default: false
  move-to-side-e:
    description:
    - Move window to right side of screen
    - Description - Schema Blank
    type: str
    default: []

  move-to-side-e_locked:
    description:
    - >
      If set to true, locks the 'move-to-side-e' key to prevent user modification.
    type: bool
    default: false
  move-to-side-w:
    description:
    - Move window to left side of screen
    - Description - Schema Blank
    type: str
    default: []

  move-to-side-w_locked:
    description:
    - >
      If set to true, locks the 'move-to-side-w' key to prevent user modification.
    type: bool
    default: false
  move-to-center:
    description:
    - Move window to center of screen
    - Description - Schema Blank
    type: str
    default: []

  move-to-center_locked:
    description:
    - >
      If set to true, locks the 'move-to-center' key to prevent user modification.
    type: bool
    default: false
  switch-input-source:
    description:
    - Switch input source
    - Binding to select the next input source
    type: str
    default:
    - Superspace
    - XF86Keyboard

  switch-input-source_locked:
    description:
    - >
      If set to true, locks the 'switch-input-source' key to prevent user modification.
    type: bool
    default: false
  switch-input-source-backward:
    description:
    - Switch input source backward
    - Binding to select the previous input source
    type: str
    default:
    - ShiftSuperspace
    - ShiftXF86Keyboard

  switch-input-source-backward_locked:
    description:
    - >
      If set to true, locks the 'switch-input-source-backward' key to prevent user modification.
    type: bool
    default: false
  always-on-top:
    description:
    - Toggle window to be always on top
    - Set or unset window to appear always on top
    type: str
    default: []

  always-on-top_locked:
    description:
    - >
      If set to true, locks the 'always-on-top' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.desktop.wm.keybindings
  org_gnome_desktop_wm_keybindings:
    switch-to-workspace-1:
    - SuperHome

    switch-to-workspace-2: []

    switch-to-workspace-3: []

    switch-to-workspace-4: []

    switch-to-workspace-5: []

    switch-to-workspace-6: []

    switch-to-workspace-7: []

    switch-to-workspace-8: []

    switch-to-workspace-9: []

    switch-to-workspace-10: []

    switch-to-workspace-11: []

    switch-to-workspace-12: []

    switch-to-workspace-left:
    - SuperPage_Up
    - SuperAltLeft
    - ControlAltLeft

    switch-to-workspace-right:
    - SuperPage_Down
    - SuperAltRight
    - ControlAltRight

    switch-to-workspace-up:
    - ControlAltUp

    switch-to-workspace-down:
    - ControlAltDown

    switch-to-workspace-last:
    - SuperEnd

    switch-group:
    - SuperAbove_Tab
    - AltAbove_Tab

    switch-group-backward:
    - ShiftSuperAbove_Tab
    - ShiftAltAbove_Tab

    switch-applications:
    - SuperTab
    - AltTab

    switch-applications-backward:
    - ShiftSuperTab
    - ShiftAltTab

    switch-windows: []

    switch-windows-backward: []

    switch-panels:
    - ControlAltTab

    switch-panels-backward:
    - ShiftControlAltTab

    cycle-group:
    - AltF6

    cycle-group-backward:
    - ShiftAltF6

    cycle-windows:
    - AltEscape

    cycle-windows-backward:
    - ShiftAltEscape

    cycle-panels:
    - ControlAltEscape

    cycle-panels-backward:
    - ShiftControlAltEscape

    show-desktop: []

    panel-main-menu: []

    panel-run-dialog:
    - AltF2

    set-spew-mark: []

    activate-window-menu:
    - Altspace

    toggle-fullscreen: []

    toggle-maximized:
    - AltF10

    toggle-above: []

    maximize:
    - SuperUp

    unmaximize:
    - SuperDown
    - AltF5

    minimize:
    - Superh

    close:
    - AltF4

    begin-move:
    - AltF7

    begin-resize:
    - AltF8

    toggle-on-all-workspaces: []

    move-to-workspace-1:
    - SuperShiftHome

    move-to-workspace-2: []

    move-to-workspace-3: []

    move-to-workspace-4: []

    move-to-workspace-5: []

    move-to-workspace-6: []

    move-to-workspace-7: []

    move-to-workspace-8: []

    move-to-workspace-9: []

    move-to-workspace-10: []

    move-to-workspace-11: []

    move-to-workspace-12: []

    move-to-workspace-last:
    - SuperShiftEnd

    move-to-workspace-left:
    - SuperShiftPage_Up
    - SuperShiftAltLeft
    - ControlShiftAltLeft

    move-to-workspace-right:
    - SuperShiftPage_Down
    - SuperShiftAltRight
    - ControlShiftAltRight

    move-to-workspace-up:
    - ControlShiftAltUp

    move-to-workspace-down:
    - ControlShiftAltDown

    move-to-monitor-left:
    - SuperShiftLeft

    move-to-monitor-right:
    - SuperShiftRight

    move-to-monitor-up:
    - SuperShiftUp

    move-to-monitor-down:
    - SuperShiftDown

    raise-or-lower: []

    raise: []

    lower: []

    maximize-vertically: []

    maximize-horizontally: []

    move-to-corner-nw: []

    move-to-corner-ne: []

    move-to-corner-sw: []

    move-to-corner-se: []

    move-to-side-n: []

    move-to-side-s: []

    move-to-side-e: []

    move-to-side-w: []

    move-to-center: []

    switch-input-source:
    - Superspace
    - XF86Keyboard

    switch-input-source-backward:
    - ShiftSuperspace
    - ShiftXF86Keyboard

    always-on-top: []

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'switch-to-workspace-1': {
            'default': ['SuperHome'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-2': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-3': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-4': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-5': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-6': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-7': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-8': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-9': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-10': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-11': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-12': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-left': {
            'default': ['SuperPage_Up', 'SuperAltLeft', 'ControlAltLeft'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-right': {
            'default': ['SuperPage_Down', 'SuperAltRight', 'ControlAltRight'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-up': {
            'default': ['ControlAltUp'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-down': {
            'default': ['ControlAltDown'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-to-workspace-last': {
            'default': ['SuperEnd'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-group': {
            'default': ['SuperAbove_Tab', 'AltAbove_Tab'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-group-backward': {
            'default': ['ShiftSuperAbove_Tab', 'ShiftAltAbove_Tab'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-applications': {
            'default': ['SuperTab', 'AltTab'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-applications-backward': {
            'default': ['ShiftSuperTab', 'ShiftAltTab'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-windows': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-windows-backward': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-panels': {
            'default': ['ControlAltTab'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-panels-backward': {
            'default': ['ShiftControlAltTab'],
            'type': 'str',
            'gtype':'as',
        },
        'cycle-group': {
            'default': ['AltF6'],
            'type': 'str',
            'gtype':'as',
        },
        'cycle-group-backward': {
            'default': ['ShiftAltF6'],
            'type': 'str',
            'gtype':'as',
        },
        'cycle-windows': {
            'default': ['AltEscape'],
            'type': 'str',
            'gtype':'as',
        },
        'cycle-windows-backward': {
            'default': ['ShiftAltEscape'],
            'type': 'str',
            'gtype':'as',
        },
        'cycle-panels': {
            'default': ['ControlAltEscape'],
            'type': 'str',
            'gtype':'as',
        },
        'cycle-panels-backward': {
            'default': ['ShiftControlAltEscape'],
            'type': 'str',
            'gtype':'as',
        },
        'show-desktop': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'panel-main-menu': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'panel-run-dialog': {
            'default': ['AltF2'],
            'type': 'str',
            'gtype':'as',
        },
        'set-spew-mark': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'activate-window-menu': {
            'default': ['Altspace'],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-fullscreen': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-maximized': {
            'default': ['AltF10'],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-above': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'maximize': {
            'default': ['SuperUp'],
            'type': 'str',
            'gtype':'as',
        },
        'unmaximize': {
            'default': ['SuperDown', 'AltF5'],
            'type': 'str',
            'gtype':'as',
        },
        'minimize': {
            'default': ['Superh'],
            'type': 'str',
            'gtype':'as',
        },
        'close': {
            'default': ['AltF4'],
            'type': 'str',
            'gtype':'as',
        },
        'begin-move': {
            'default': ['AltF7'],
            'type': 'str',
            'gtype':'as',
        },
        'begin-resize': {
            'default': ['AltF8'],
            'type': 'str',
            'gtype':'as',
        },
        'toggle-on-all-workspaces': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-1': {
            'default': ['SuperShiftHome'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-2': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-3': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-4': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-5': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-6': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-7': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-8': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-9': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-10': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-11': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-12': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-last': {
            'default': ['SuperShiftEnd'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-left': {
            'default': ['SuperShiftPage_Up', 'SuperShiftAltLeft', 'ControlShiftAltLeft'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-right': {
            'default': ['SuperShiftPage_Down', 'SuperShiftAltRight', 'ControlShiftAltRight'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-up': {
            'default': ['ControlShiftAltUp'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-workspace-down': {
            'default': ['ControlShiftAltDown'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-monitor-left': {
            'default': ['SuperShiftLeft'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-monitor-right': {
            'default': ['SuperShiftRight'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-monitor-up': {
            'default': ['SuperShiftUp'],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-monitor-down': {
            'default': ['SuperShiftDown'],
            'type': 'str',
            'gtype':'as',
        },
        'raise-or-lower': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'raise': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'lower': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'maximize-vertically': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'maximize-horizontally': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-corner-nw': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-corner-ne': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-corner-sw': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-corner-se': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-side-n': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-side-s': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-side-e': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-side-w': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'move-to-center': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
        'switch-input-source': {
            'default': ['Superspace', 'XF86Keyboard'],
            'type': 'str',
            'gtype':'as',
        },
        'switch-input-source-backward': {
            'default': ['ShiftSuperspace', 'ShiftXF86Keyboard'],
            'type': 'str',
            'gtype':'as',
        },
        'always-on-top': {
            'default': [],
            'type': 'str',
            'gtype':'as',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.desktop.wm.keybindings")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.desktop.wm.keybindings")

    schema_full_path = "/org/gnome/desktop/wm/keybindings/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []
    gvariant_converter = GVariantValueConverter()
    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)
        
        new_value = gvariant_converter.parse_value_string(setting_value, spec['gtype'])
        new_settings.set(config_section, key_name, new_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
