#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_desktop_background
short_description: Manages GNOME GSettings for org.gnome.desktop.background
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.desktop.background' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.1.0"
options:
  picture-options:
    description:
    - Picture Options
    - "Determines how the image set by wallpaper_filename is rendered.\n        Possible\
      \ values are 'none', 'wallpaper', 'centered', 'scaled',\n        'stretched', 'zoom',\
      \ 'spanned'."
    type: str
    default: zoom

  picture-options_locked:
    description:
    - >
      If set to true, locks the 'picture-options' key to prevent user modification.
    type: bool
    default: false
  picture-uri:
    description:
    - Picture URI
    - "URI to use for the background image. Note that the backend only supports\n    \
      \    local (file://) URIs."
    type: str
    default: file:///usr/share/backgrounds/gnome/adwaita-l.jpg

  picture-uri_locked:
    description:
    - >
      If set to true, locks the 'picture-uri' key to prevent user modification.
    type: bool
    default: false
  picture-uri-dark:
    description:
    - Picture URI (dark)
    - "URI to use for the background image. Note that the backend only supports\n    \
      \    local (file://) URIs."
    type: str
    default: file:///usr/share/backgrounds/gnome/adwaita-d.jpg

  picture-uri-dark_locked:
    description:
    - >
      If set to true, locks the 'picture-uri-dark' key to prevent user modification.
    type: bool
    default: false
  picture-opacity:
    description:
    - Picture Opacity
    - Opacity with which to draw the background picture.
    type: int
    default: 100

  picture-opacity_locked:
    description:
    - >
      If set to true, locks the 'picture-opacity' key to prevent user modification.
    type: bool
    default: false
  primary-color:
    description:
    - Primary Color
    - Left or Top color when drawing gradients, or the solid color.
    type: str
    default: '#023c88'

  primary-color_locked:
    description:
    - >
      If set to true, locks the 'primary-color' key to prevent user modification.
    type: bool
    default: false
  secondary-color:
    description:
    - Secondary Color
    - Right or Bottom color when drawing gradients, not used for solid color.
    type: str
    default: '#5789ca'

  secondary-color_locked:
    description:
    - >
      If set to true, locks the 'secondary-color' key to prevent user modification.
    type: bool
    default: false
  color-shading-type:
    description:
    - Color Shading Type
    - "How to shade the background color. Possible values are 'horizontal',\n        'vertical',\
      \ and 'solid'."
    type: str
    default: solid

  color-shading-type_locked:
    description:
    - >
      If set to true, locks the 'color-shading-type' key to prevent user modification.
    type: bool
    default: false
  show-desktop-icons:
    description:
    - Have file manager handle the desktop
    - If set to true, then file manager will draw the icons on the desktop.
    type: bool
    default: false

  show-desktop-icons_locked:
    description:
    - >
      If set to true, locks the 'show-desktop-icons' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.desktop.background
  org_gnome_desktop_background:
    picture-options: zoom

    picture-uri: file:///usr/share/backgrounds/gnome/adwaita-l.jpg

    picture-uri-dark: file:///usr/share/backgrounds/gnome/adwaita-d.jpg

    picture-opacity: 100

    primary-color: '#023c88'

    secondary-color: '#5789ca'

    color-shading-type: solid

    show-desktop-icons: false

'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""
    # We have to do gross stuff with the bools here.
    keys_spec = {
        'picture-options': {
            'default': 'zoom',
            'type': 'str',
            'gtype':'s',
        },
        'picture-uri': {
            'default': 'file:///usr/share/backgrounds/gnome/adwaita-l.jpg',
            'type': 'str',
            'gtype':'s',
        },
        'picture-uri-dark': {
            'default': 'file:///usr/share/backgrounds/gnome/adwaita-d.jpg',
            'type': 'str',
            'gtype':'s',
        },
        'picture-opacity': {
            'default': 100,
            'type': 'int',
            'gtype':'i',
        },
        'primary-color': {
            'default': '#023c88',
            'type': 'str',
            'gtype':'s',
        },
        'secondary-color': {
            'default': '#5789ca',
            'type': 'str',
            'gtype':'s',
        },
        'color-shading-type': {
            'default': 'solid',
            'type': 'str',
            'gtype':'s',
        },
        'show-desktop-icons': {
            'default': False,
            'type': 'bool',
            'gtype':'b',
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org.gnome.desktop.background")
    lock_file_path = os.path.join(locks_dir, "ansible-org.gnome.desktop.background")

    schema_full_path = "/org/gnome/desktop/background/"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f'{param_value}'
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
