#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2023, Jules
# All rights reserved.

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: org_gnome_settings-daemon_peripherals_wacom_deprecated
short_description: Manages GNOME GSettings for org.gnome.settings-daemon.peripherals.wacom.deprecated
description:
  - >
    This module allows for the configuration of GSettings keys within the 'org.gnome.settings-daemon.peripherals.wacom.deprecated' schema.
  - >
    It supports setting default values and locking keys to enforce system-wide policies.
author:
  - Autogenerated by ansible-gnome-lockdown
version_added: "1.0.0"
options:
  is-absolute:
    description:
      - >
        Wacom stylus absolute mode
      - >
        Enable this to set the tablet to absolute mode.
    type: bool
    default: true
  is-absolute_locked:
    description:
      - >
        If set to true, locks the 'is-absolute' key to prevent user modification.
    type: bool
    default: false
  area:
    description:
      - >
        Wacom tablet area
      - >
        Set this to x1, y1 and x2, y2 of the area usable by the tools.
    type: str
    default: "[-1, -1, -1, -1]"
  area_locked:
    description:
      - >
        If set to true, locks the 'area' key to prevent user modification.
    type: bool
    default: false
  keep-aspect:
    description:
      - >
        Wacom tablet aspect ratio
      - >
        Enable this to restrict the Wacom tablet area to match the aspect ratio of the output.
    type: bool
    default: false
  keep-aspect_locked:
    description:
      - >
        If set to true, locks the 'keep-aspect' key to prevent user modification.
    type: bool
    default: false
  rotation:
    description:
      - >
        Wacom tablet rotation
      - >
        Set this to “none”, “cw” for 90 degree clockwise, “half” for 180 degree, and “ccw” for 90 degree counterclockwise.
    type: str
    default: "none"
  rotation_locked:
    description:
      - >
        If set to true, locks the 'rotation' key to prevent user modification.
    type: bool
    default: false
  touch:
    description:
      - >
        Wacom touch feature
      - >
        Enable this to move the cursor when the user touches the tablet.
    type: bool
    default: true
  touch_locked:
    description:
      - >
        If set to true, locks the 'touch' key to prevent user modification.
    type: bool
    default: false
'''

EXAMPLES = r'''
- name: Configure and lock GNOME desktop settings for org.gnome.settings-daemon.peripherals.wacom.deprecated
  org_gnome_settings-daemon_peripherals_wacom_deprecated:
    is-absolute: true
    is-absolute_locked: true
    area: "[-1, -1, -1, -1]"
    area_locked: true
'''

RETURN = r'''
# Default return values
'''

from ansible.module_utils.basic import AnsibleModule
import os
import configparser

def main():
    """Main function for the Ansible module."""

    keys_spec = {
        'is-absolute': {
            'type': 'bool',
            'default': True
        },
        'area': {
            'type': 'str',
            'default': "[-1, -1, -1, -1]"
        },
        'keep-aspect': {
            'type': 'bool',
            'default': True
        },
        'rotation': {
            'type': 'str',
            'default': "none"
        },
        'touch': {
            'type': 'bool',
            'default': True
        },
    }

    argument_spec = {}
    for key_name, spec in keys_spec.items():
        argument_spec[key_name] = spec
        argument_spec[f"{key_name}_locked"] = {'type': 'bool', 'default': False}

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True
    )

    changed = False

    settings_dir = "/etc/dconf/db/local.d"
    locks_dir = os.path.join(settings_dir, "locks")

    settings_file_path = os.path.join(settings_dir, "00-ansible-org_gnome_settings-daemon_peripherals_wacom_deprecated")
    lock_file_path = os.path.join(locks_dir, "ansible-org_gnome_settings-daemon_peripherals_wacom_deprecated")

    schema_full_path = "None"
    config_section = schema_full_path.strip('/')

    os.makedirs(settings_dir, exist_ok=True)
    os.makedirs(locks_dir, exist_ok=True)

    # Idempotency: Read current settings
    current_settings = configparser.ConfigParser()
    if os.path.exists(settings_file_path):
        current_settings.read(settings_file_path)

    # Idempotency: Read current locks from our dedicated lock file
    current_locks = []
    if os.path.exists(lock_file_path):
        with open(lock_file_path, 'r') as f:
            current_locks = [line.strip() for line in f if line.strip()]

    # Prepare settings and locks based on module parameters
    new_settings = configparser.ConfigParser()
    new_settings.add_section(config_section)
    new_locks = []

    for key_name, spec in keys_spec.items():
        param_value = module.params[key_name]
        param_locked = module.params[f"{key_name}_locked"]

        if spec['type'] == 'bool':
            setting_value = str(param_value).lower()
        elif spec['type'] == 'str':
            setting_value = f"'{param_value}'"
        else:
            setting_value = str(param_value)

        new_settings.set(config_section, key_name, setting_value)

        if param_locked:
            new_locks.append(f"{schema_full_path}{key_name}")

    # Check for changes
    settings_changed = False
    if not current_settings.has_section(config_section) or \
       (current_settings.has_section(config_section) and dict(current_settings.items(config_section)) != dict(new_settings.items(config_section))):
        settings_changed = True

    locks_changed = sorted(new_locks) != sorted(current_locks)

    if settings_changed or locks_changed:
        changed = True

    if changed and not module.check_mode:
        # Write settings file
        with open(settings_file_path, 'w') as f:
            new_settings.write(f, space_around_delimiters=False)

        # Manage the dedicated lock file
        if new_locks:
            with open(lock_file_path, 'w') as f:
                for lock_key in new_locks:
                    f.write(f"{lock_key}\n")
        elif os.path.exists(lock_file_path):
            os.remove(lock_file_path)

        # Update dconf database
        module.run_command(["dconf", "update"], check_rc=True)

    module.exit_json(changed=changed)

if __name__ == '__main__':
    main()
